### ISSUE TITLE
关于显示器的配置修改

### ISSUE THREAD

**Issue by ednow** [xianyukang/MyKeymap#10]
请问怎么做到修改亮度的呢，想定制一些别的功能，比如我的显示器还可以修改滤蓝光等级，显示模式啥的

**Comment by xianyukang** [comment]
调整亮度调用的 Windows API: https://docs.microsoft.com/en-us/windows/win32/api/highlevelmonitorconfigurationapi/nf-highlevelmonitorconfigurationapi-setmonitorcontrast

显示器的特色功能比如滤蓝光等级,  可能需要下载显示器供应商提供的控制软件 (如果提供了的话)
