### ISSUE TITLE
与quicker似乎存在一定的冲突

### ISSUE THREAD

**Issue by ywg814** [xianyukang/MyKeymap#100]
您好，这款软件的开发非常让人喜欢。感谢作者的付出！
我在win10下同时使用这款软件和quicker时，似乎出现了一些冲突。我使用quicker自定义了一个手势用来切换应用程序，对应的快捷键是：ctrl alt tab。但是当Mykeymap运行时，这一手势的作用变成了ctrl tab，只用于切换标签页。当然，我直接在键盘上使用快捷键时，一切正常。当我暂停使用MyKeymap后，手势作用也会恢复正常。我并不确定是哪一款软件出现了冲突。

**Comment by xianyukang** [comment]
- 实测是「 自定义热键 」中把「 RAlt 」重映射为「 LCtrl 」导致了冲突
- 你可以删掉这个映射

**Comment by lyc118** [comment]
![Image](https://github.com/user-attachments/assets/150cfabc-0fec-4a72-9248-26da462f8843)请问是这样吗，我也是开了map就运行不了quicker

**Comment by lyc118** [comment]
> ![Image](https://github.com/user-attachments/assets/150cfabc-0fec-4a72-9248-26da462f8843)请问是这样吗，我也是开了map就运行不了quicker

如果不对的话，可以的话能按步骤来截图不哥哥，我是傻子(ㄒoㄒ)
