### ISSUE TITLE
amazon workspace 全屏状态下如何识别原系统快捷键？

### ISSUE THREAD

**Issue by ThomasLi10** [xianyukang/MyKeymap#103]
我现在有个痛点是这样的：平时主要在 amazon workspace （windows 系统）中工作，同时时不时地需要切回 PC 原系统。但全屏进入 workspace 后，所有的快捷键都会重定向成 workspace 的 windows 系统的快捷键，无法使用任何方法返回原系统。请问 MyKeymap 有解决办法吗？谢谢！

**Comment by xianyukang** [comment]
1. 暂未找到办法
2. 不清楚这个有没有用: https://stackoverflow.com/q/43747838
