### ISSUE TITLE
2.0Beta 之后右键与 Mouselnc 右键手势冲突

### ISSUE THREAD

**Issue by arpir** [xianyukang/MyKeymap#104]
1.2 版本的时候不会冲突。

**Comment by arpir** [comment]
另外一个感觉就是2.0 beta的按键、内置函数这些改变好大啊，以前的案例都不适用了。

**Comment by gdzrh917** [comment]
你好，我也发现跟右键手势冲突，如何解决的呢？

**Comment by gdzrh917** [comment]
研究了一下，将右键的触发键修改为：“~rbutton” 即可

**Comment by arpir** [comment]
> 研究了一下，将右键的触发键修改为：「~rbutton」 ，同时将 SinglePress 改为未配置，否则在手势后会触发右键。

我之前把ISSUE关了是因为用不换2.0之后的版本，现在已经迁移到2.0之后的版本了，右键的功能因为冲突就把它关闭了，看到你的回复又过来研究一下，你说的「右键的触发键修改为：~rbutton」，是在自定义热键这里修改吗？

**Comment by arpir** [comment]
> > 研究了一下，将右键的触发键修改为：「~rbutton」 ，同时将 SinglePress 改为未配置，否则在手势后会触发右键。
> 
> 我之前把 ISSUE 关了是因为用不惯 2.0 之后的版本，现在已经迁移到 2.0 之后的版本了，右键的功能因为冲突就把它关闭了，看到你的回复又过来研究一下，你说的「右键的触发键修改为：~rbutton」，是在自定义热键这里修改吗？

经过这么修改右键是回来了但是还是与Mouselnc的右键手势冲突，1.2版本没有这个问题

**Comment by xianyukang** [comment]
是有冲突啊，也许是升级到 Autohotkey 2.0 导致的问题，推荐在设置里关掉 MyKeymap 的「 鼠标右键 」

**Comment by arpir** [comment]
> 是有冲突啊，也许是升级到 Autohotkey 2.0 导致的问题，推荐在设置里关掉 MyKeymap 的「 鼠标右键 」

嗯嗯，目前也是关闭了MyKeymap 的「 鼠标右键 」功能，看之后能解决这个问题……

**Comment by xianyukang** [comment]
@arpir 试试 beta21 版本，应该能兼容 MouseInc 鼠标手势
