### ISSUE TITLE
[bug] 升级新版本时出现bug

### ISSUE THREAD

**Issue by feitian6186** [xianyukang/MyKeymap#105]
大佬
      你好！mykeymap 从1.2.7 升级到 2.0.0-bata15时，出现bug具体如下图。
      
![image](https://github.com/xianyukang/MyKeymap/assets/42461871/c2bdb819-18cb-45ea-8054-6c1309746319)
  
  同时希望保留模拟 Alt+Tab 功能

**Comment by xianyukang** [comment]
1. 配置文件结构改了很多，不支持从版本 1 升级到版本 2，需要重配
2. 推荐用这个功能替代，按法和 Alt+Tab 热键一样，但需要按一次空格键确认
3. 有个额外的好处，当窗口多时能用 EDSF 切换上下左右，还能用 X 关闭窗口
![image](https://github.com/xianyukang/MyKeymap/assets/24707226/78ff8971-3f39-4e17-bc8b-efe3bd9867ca)
