### ISSUE TITLE
Capslock 模式怎么绑定到Win按键上？

### ISSUE THREAD

**Issue by Ocyss** [xianyukang/MyKeymap#108]
如题

**Comment by xianyukang** [comment]
可以这样配:
![image](https://github.com/xianyukang/MyKeymap/assets/24707226/fe3981fe-b003-43d0-bddf-05d6fc43778c)


但不推荐用 Win 键，一个原因是 Win 键难按，另一个原因是系统不允许覆盖 Win+L 热键。

**Comment by Ocyss** [comment]
从Linux转来的，用习惯了~

**Comment by Ocyss** [comment]
试了下，有bug，按了Win打开了命令框在按win不会关闭命令框，而是打开WIn开始菜单

**Comment by xianyukang** [comment]
可以用 Esc 键退出
