### ISSUE TITLE
关于某些键位无法设置的疑问

### ISSUE THREAD

**Issue by MasouShizuka** [xianyukang/MyKeymap#11]
在键位功能的设置中，有些键位是灰色的，无法设置
比如`Capslock`页面的`Z`、`F`、`Space`

因为写死了`Capslock + F`，我能理解不能映射`F`，但其他的键位为什么不可以映射呢，因为每个模式都有自己的前缀，应该不会冲突才对
其他的模式也有一些灰色的无法映射的键位

如果可以的话，希望能够开放这些键位的设置

**Comment by xianyukang** [comment]
个人体验下来,  不太好按,  所以置灰了

**Comment by xianyukang** [comment]
比如 Caps + Z,  实在太难按了

**Comment by MasouShizuka** [comment]
确实，这些灰色的地方有些不好按
但是，没必要就彻底禁止使用

比如，我可以把小键盘映射到左边的9个键位，即qweasdzxc
这也能多些用户自己的选择，只需要默认不添加功能就可以了

**Comment by xianyukang** [comment]
好的,  对按键分配的限制会放松。

**Comment by xianyukang** [comment]
减少置灰的按键: https://github.com/xianyukang/MyKeymap/commit/cfc2db2811cbc88867a8898c865642dd2d026fc9
