### ISSUE TITLE
[功能提议] 原快捷键保留，长按触发等

### ISSUE THREAD

**Issue by Ocyss** [xianyukang/MyKeymap#110]
1.  不配置则为原功能
	> 比如触发键是WIn，即使什么都不配置也会让原先快捷键全部失效
	 单键，不配置原功能
	 多键，不配置原快捷键
2.  长按是否多次触发设置
	> 部分命令不希望长按多次触发，比如窗口类，但输入文本可能需要，输入命令/快捷键又不需要
3.  长按/短按，不同指令
	> 自定义长按时间，长按显示光圈（随便哪种提醒）？到了之后松开则触发长按命令，比如我可以Win+W短按最大/还原，长按关闭应用程序
3. 奇思妙想，说说而已
	> 灰色按钮强制点亮，隐藏元素显示
	强制杀死目标应用
	窗口级别的音量控制与静音
	透明度调整

前几个功能，按理来讲不是很难，等我琢磨完源码，有时间就提pr

**Comment by alexcchen** [comment]
鼠标移动键第一次触发可以默认为短距离或者没有距离吗？有时候鼠标需要移动的距离非常小，但是由于默认第一次触发一定是按着触发键是大距离移动，导致鼠标移开过远，需要多次微调鼠标到目标位置

**Comment by xianyukang** [comment]
> 鼠标移动键第一次触发可以默认为短距离或者没有距离吗？有时候鼠标需要移动的距离非常小，但是由于默认第一次触发一定是按着触发键是大距离移动，导致鼠标移开过远，需要多次微调鼠标到目标位置

- 使用默认键位的话，按 Capslock + JL 就是原地了，也就是左移一下再右移一下
