### ISSUE TITLE
如何导出配置或者导入配置

### ISSUE THREAD

**Issue by qwe1433223** [xianyukang/MyKeymap#115]
我在这个文件里更改并且重启程序后，配置并没有更新到keymap上。如何批量修改配置？
快捷映射MyKeymap\data\config.json

**Comment by xianyukang** [comment]
可以用网页修改配置，这里的「 批量修改配置 」是指什么?

**Comment by alexcchen** [comment]
下载了新版本的mykeymap，旧版本的按键配置数据，是否可以直接复制旧版本文件下方的data文件夹，到新版文件夹下替换data文件夹就好了吗？不然全部重新设置一遍稍微麻烦了

**Comment by xianyukang** [comment]
@alexcchen 替换 data 文件夹就行

**Comment by Faith-Mian** [comment]
> @alexcchen* 替换 data 文件夹就行

配置迁移到新版报错呀

关于custom_functions.ahk，用旧的覆盖并启动mykeymap2.0，send这一行会报错

旧版的内容如下：
sendSomeChinese() {
    send, {text}你好中文!
}
新版的内容如下：
sendSomeChinese() {
  Send("{text}你好中文!")
}
---

另关于配置文件，直接用旧的覆盖会报错030: slow := MouseKeymap("slow mouse", false, mouseTip, , , "T", "T", , "T", "T")
