### ISSUE TITLE
【功能建议】关于用户自定义设置

### ISSUE THREAD

**Issue by QwindF** [xianyukang/MyKeymap#119]
原因：软件默认自带的规则可能不够个性化，所以用户会自己修改规则，但是可能会出现很多台电脑规则不同步的情况。
最好的想法当然是进行同步规则。
希望这些规则可以导出成json或者其他格式，然后一键导入到其他电脑上。或者制作成订阅链接，可以备份跟新。

**Comment by xianyukang** [comment]
软件是绿色软件，把 MyKeymap 文件夹放到同步盘里面就行了，onedrive 或坚果云都行
