### ISSUE TITLE
关于Capslock单键映射的建议

### ISSUE THREAD

**Issue by MasouShizuka** [xianyukang/MyKeymap#12]
本工具只针对按住`Capslock`，单独按一下还是如原来一样会开启大写锁定

希望能够添加对于单按`Capslock`的映射功能

比如对于`vim`用户，用`Capslock`代替`Esc`非常常用

---

顺便一提，本人已经使用`Powertoys`的键盘管理器将`Capslock`映射成`Esc`，这种情况下，两者只有一个有效
若在打开`Powertoys`键盘管理器的情况下打开本工具，则前者失效；
若在打开本工具的情况下将`Powertoys`键盘管理器关闭又打开，则本工具失效

**Comment by xianyukang** [comment]
以后会让特殊键可配置,  比如「 单按 Caps 」、「 单按 3 」、「 单按分号 」....

( 个人没有遇到 Caps 和 Esc 的抉择问题,  因为我用 `J + X` 输入 `Esc` 键

**Comment by MasouShizuka** [comment]
单按分号应该不可行把，这样不会默认禁止`分号缩写`的模式吗

**Comment by xianyukang** [comment]
有道理, 有道理。

**Comment by MasouShizuka** [comment]
不好意思，又想到一点，就不开新issue了

因为您提到了单按`3`，那就干脆把剩下的键位都加上把
![image](https://user-images.githubusercontent.com/44764707/141305681-860bc16c-8241-417a-8600-283dc340bab9.png)
![image](https://user-images.githubusercontent.com/44764707/141305402-4867b3f3-d7c2-4458-a4a0-a3fd63fc3ad7.png)

比如，还剩下`1-0`、`-`、`+`、`[`、`]`、'\'、`'`等
这样可以作为一个更全面的改键位工具

**Comment by xianyukang** [comment]
1.0.25 增加了数字键用于自定义。

**Comment by bcaso** [comment]
> 本工具只针对按住`Capslock`，单独按一下还是如原来一样会开启大写锁定
> 
> 希望能够添加对于单按`Capslock`的映射功能
> 
> 比如对于`vim`用户，用`Capslock`代替`Esc`非常常用
> 
> 顺便一提，本人已经使用`Powertoys`的键盘管理器将`Capslock`映射成`Esc`，这种情况下，两者只有一个有效 若在打开`Powertoys`键盘管理器的情况下打开本工具，则前者失效； 若在打开本工具的情况下将`Powertoys`键盘管理器关闭又打开，则本工具失效

对于 vim 或 emacs 用户，高效利用 `Capslock` 这个位置，可以将其映射为 `Ctrl`, 这样 `ctrl+c`, `ctrl+a`, `ctrl+f` 等文本编辑时非常方便，这样的映射对 Emacs 用户也很方便。

对于 退出编辑模式，可以用 `ctrl+[`，这是 vim 默认的设置。
