### ISSUE TITLE
xbutton1怎么没法用？

### ISSUE THREAD

**Issue by lymyxhw** [xianyukang/MyKeymap#120]
MyKeymap-2.0-beta19，xbutton1模式完全没反应，测试过xbutton1能识别，也没坏，关闭其他脚本也不行，谢谢

**Comment by xianyukang** [comment]
提供一下复现步骤，复现了才好分析问题

**Comment by lymyxhw** [comment]
![image](https://github.com/xianyukang/MyKeymap/assets/26971401/2ac1b3ef-2f37-4867-ad82-341fbd1b4fbc)
![image](https://github.com/xianyukang/MyKeymap/assets/26971401/e32aab31-5bfc-48d7-872d-40a6da2b230a)
定义的快捷键没有反应，如果用其他模式都没问题，就xbutton1模式没反应

**Comment by xianyukang** [comment]
按图中的配置，我这边测试没问题，现在只能猜原因了:
1. 有两个鼠标侧键，误按了另一个侧键
2. 鼠标侧键已经在驱动程序中映射成了别的功能
3. 鼠标侧键被其他鼠标手势软件占用了

**Comment by mekefly** [comment]
我想，可尝试重启一下软件

**Comment by lymyxhw** [comment]
其实都试了，xbutton1在别的模式下是能响应的，但是单独作为模式开始按键就不行，我放在虚拟机里运行也不行，我属实找不到问题，先不用这个模式了

**Comment by R4x7651** [comment]
我也遇到了这个情况，不过已经解决了，罗技g系列鼠标，原因是罗技默认的侧键绑定为go forward和go back，把这两个键绑定为“前进”和“后退”就好了

<img width="1819" height="1378" alt="Image" src="https://github.com/user-attachments/assets/7802d248-235d-4027-8487-463a14e2dc92" />
