### ISSUE TITLE
[问题反馈]   音量控制无法打开

### ISSUE THREAD

**Issue by clpbc** [xianyukang/MyKeymap#121]
一使用音量控制就显示出现错误，无法打开

**Comment by alexcchen** [comment]
最近发现笔记本不会自动进入睡眠模式和休眠模式，笔记本放了一晚上，一点击键盘，发现只是屏幕熄屏了，都没有自动锁屏（当然可以人走随手锁屏，但总会忘记），存在一定的隐私风险和耗能，网上搜索到如何查看哪个软件阻止熄屏，按照教程使用管理员cmd输入powercfg -requests，查看到阻止熄屏的是音频驱动，具体如下
SYSTEM:
IDRIVER] Realtek High Definition Audio (HDAUDIO FUNC 01&VEN 10EC&DEV 0295&SUBSYS 103C8575&REV 1000 4&2dd1916aO&0001)
音频流当前正在使用中。
然后我关闭退出mykeymap软件后，再次查询，结果如下
SYSTEM:
无。
又打开mykeymap软件，再次运行cmd命令查询，结果又是查询到音频驱动阻止熄屏
SYSTEM:
IDRIVER] Realtek High Definition Audio (HDAUDIO FUNC 01&VEN 10EC&DEV 0295&SUBSYS 103C8575&REV 1000 4&2dd1916aO&0001)
音频流当前正在使用中。
目前推测可能是mykeymap会持续调用该音频驱动，导致了系统不进入睡眠模式，不知道是否有可能解决该问题，好让笔记本自动锁屏进入睡眠休眠模式。

**Comment by alexcchen** [comment]
解决了
