### ISSUE TITLE
[功能建议] 显示器亮度调节预设模式

### ISSUE THREAD

**Issue by lymyxhw** [xianyukang/MyKeymap#122]
经常带着电脑在两个位置工作，每次都要切换亮度，能不能提供一个函数，一键切换显示器亮度，或者亮度调节预设，可以直接切换模式来改亮度。
如果已有类似操作还请告知一下，谢谢谢谢，真的非常好用的软件！

**Comment by alexcchen** [comment]
可以映射按键功能为 ”系统设置“-”显示器亮度调节“功能，进入后就是edsf调节亮度，c退出，暂时没找到快捷键一建映射到预设亮度的方法

**Comment by lymyxhw** [comment]
收到，感谢
