### ISSUE TITLE
怎么修改默认的组合按键

### ISSUE THREAD

**Issue by luo-zhan** [xianyukang/MyKeymap#123]
比如句号模式，不想使用句号，想改成使用 **右ctrl**来组合，有办法修改吗

**Comment by xianyukang** [comment]
这里可以改成 `*RCtrl`，是不是之前看漏了? 🐶
![image](https://github.com/xianyukang/MyKeymap/assets/24707226/0a0a958d-7f3a-4068-b695-ce8fc9808fbb)

**Comment by luo-zhan** [comment]
> * 这里可以改成 `*RCtrl`，是不是之前看漏了? 🐶
> * 另外 RCtrl 可能不怎么好按
> 
> ![image](https://user-images.githubusercontent.com/24707226/280986732-0a0a958d-7f3a-4068-b695-ce8fc9808fbb.png)

好像没有在使用指南里找到这个说明，而且确实也不知道右ctrl要写成`*RCtrl`，感觉设置里面的按键部分可以做成下拉框供选择呢。
另外 ，改成`*RCtrl`后，没起作用，原先的句号功能也不能用了。。。
