### ISSUE TITLE
请求发布到 GitHub Release

### ISSUE THREAD

**Issue by gdm257** [xianyukang/MyKeymap#124]
目前发布是用蓝奏云，更新起来不方便。是否考虑同时发布到 GitHub Release，这样 scoop/winget 用户可以一键安装或更新

**Comment by xianyukang** [comment]
➤ 发布到 GitHub Release 不方便看下载数:
![image](https://github.com/xianyukang/MyKeymap/assets/24707226/6aa551fe-f43d-4360-a188-ddaf3ec3341a)

**Comment by Faith-Mian** [comment]
我看有的作者发布一个固定的蓝奏云链接，可能是共享一个文件夹，再把新版本放到文件夹里，所以链接不用变还能一直更新？
