### ISSUE TITLE
使用求助

### ISSUE THREAD

**Issue by alexcchen** [xianyukang/MyKeymap#125]
{blind}{LAlt}{LWin}{d}想要重映射为组合键看时间日期，但是设置了屏幕一闪就没了，是否需要添加延时，实际按下有延时如何添加延时

**Comment by xianyukang** [comment]
你的写法不太对，这种写法是依次按 Alt、Win、D 键，你需要的是 Alt+Win+D 组合键
关于怎么输入组合键，在欢迎界面往下拉，就有简易教程

**Comment by alexcchen** [comment]
{LWin down}{LAlt down}{d down}{LWin up}{LAlt up}{d up}

**Comment by alexcchen** [comment]
!#{d down}
sleep 10
{d up}
sleep 10
