### ISSUE TITLE
[Bug] 打开了分号模式后，冒号和分号键不能输入

### ISSUE THREAD

**Issue by zhizhijiejie** [xianyukang/MyKeymap#126]
康神，用你的软件已经好一段时间了，很感谢你分享这个程序出来
给我码字的效率提高了很多，感谢~~~

我遇到的问题是这样的

在设置页面中打开了分号模式
设置了按键D和F是切换上一个和下一个桌面
Q为edge关闭标签页
W为ctrl+tab
Z为切换上一个窗口

保存重启mykeymap
分号按键不能正常输入
重启程序也不行

**Comment by xianyukang** [comment]
把分号模式中的 `SinglePress` 键配成输入 `{blind};`

**Comment by zhizhijiejie** [comment]
请问是在哪里配置啊？
按键重映射那里吗？
SinglePress::{blind}这样写吗

**Comment by xianyukang** [comment]
> 请问是在哪里配置啊？ 按键重映射那里吗？ SinglePress::{blind}这样写吗

动作类别是「 输入文本或按键 」
