### ISSUE TITLE
热键冲突怎么解决呢？

### ISSUE THREAD

**Issue by FlickerMi** [xianyukang/MyKeymap#127]
感谢大佬，工具非常棒！不过我遇到了一些问题请教一下。
我希望将Alt键设置为Ctrl键（可通过Alt+C、Alt+V来完成复制操作），同时也希望通过Alt+Tab来切换窗口，
所以我将 LAlt 映射成 Ctrl，然后设置了一个热键映射 Ctrl+Tab -> Alt+Tab ，但是目前这样设置不行，按Alt+Tab还是Ctrl+Tab的效果，不知道是不是热键冲突，有解决办法或者设置热键优先级吗？
![Snipaste_2023-11-13_23-24-08.png](https://img1.imgtp.com/2023/11/13/pNYfDSNz.png)

**Comment by xianyukang** [comment]
不用重映射，这样影响面太大了。可以添加自定义热键 `!c` 并把动作配置成输入按键 `^c`

**Comment by FlickerMi** [comment]
> 不用重映射，这样影响面太大了。可以添加自定义热键 `!c` 并把动作配置成输入按键 `^c`

之前用mac，习惯了使用comand+其它按键，不习惯使用Ctrl键，就想着直接替换。
