### ISSUE TITLE
鼠标操作的建议

### ISSUE THREAD

**Issue by zhizhijiejie** [xianyukang/MyKeymap#128]
在2.0的测试版中，发现鼠标左键按下（之后按空键松开），这个功能好像用不了，按下空键也是无法松开按住的状态

建议改为重新按下当前键，如：设置y键为这个功能，第一次按下是进入拖动状态，第二次按下松开

谢谢，希望这款软件越来越好~~一直支持

**Comment by zhizhijiejie** [comment]
还有一个建议是触发进入鼠标模式的选项
如： Capslock  键触发 + M 打开鼠标模式  再按M取消鼠标模式  鼠标模式内可以连续点击左键

**Comment by xianyukang** [comment]
1. 之后按空键松开，我用默认配置试了一下，应该没问题，你是改了什么配置吗?
2. 设置里面可以修改鼠标参数，有个选项支持连续点击鼠标，可以按空格键退出
