### ISSUE TITLE
mcafee杀毒软件会杀掉server

### ISSUE THREAD

**Issue by zhangjun9876** [xianyukang/MyKeymap#13]
你好，mcafee杀毒软件会杀掉server，我们用的mcafee版本没有信任文件夹可以添加，怎么解决呢？

**Comment by xianyukang** [comment]
杀毒软件可以添加信任文件,  [这是我为你搜索到的 mcafee 设置教程](https://webgl.blog.csdn.net/article/details/103031357?spm=1001.2101.3001.6650.1&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-1.no_search_link&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7ECTRLIST%7Edefault-1.no_search_link)
让杀毒软件信任这个文件 bin\mykeymap-settings-server\mykeymap-settings-server.exe

**Comment by zhangjun9876** [comment]
你好，谢谢你的回复，我们mcafee是企业版的，应该是被后台控制，自己做不了任何设置。发送自我的盖乐世
-------- 原始信息 --------发件人： 咸鱼阿康 ***@***.***> 日期: 2021/11/12  11:11  (GMT+08:00) 收件人： xianyukang/MyKeymap ***@***.***> 抄送： zhangjun9876 ***@***.***>, Author ***@***.***> 主题： Re: [xianyukang/MyKeymap] mcafee杀毒软件会杀掉server (Issue #13) 

杀毒软件可以添加信任文件,  这是我为你搜索到的 mcafee 设置教程

让杀毒软件信任这个文件 bin\mykeymap-settings-server\mykeymap-settings-server.exe
