### ISSUE TITLE
features request

### ISSUE THREAD

**Issue by haha85** [xianyukang/MyKeymap#131]
希望增加一个plugins目录，一个ahk v1的二进制 和一个 ahk v2的二进制，一个功能 “使用ahk1 or ahk2” 运行脚本 “枚举plugins目录，下拉列表”  这样对于自己编写的脚本，就简单复制到plugins目录中，在功能里直接选择就可以了  我现在是用运行那个功能 然后写全路径  很麻烦而且便携性丢失了  因为好像不支持相对路径，希望我表达清楚了吧，手机敲字好难

**Comment by xianyukang** [comment]
1. 可以用 ahk v1 的 exe 执行 .ahk 文件，通过命令行参数指定要执行哪个文件
2. 支持相对路径，根目录是 Mykeymap.exe 所在文件夹

**Comment by haha85** [comment]
好的  我再试试 , 我的脚本都是v2编写的 我把v2的 exe放到 Mykeymap的根目录了, 我稍后试试  命令行参数是否支持脚本的相对路径,我之前实验好像是不可以 我再试试,我之前的做法是把work directory路径设置一下
