### ISSUE TITLE
小问题，“窗口管理”功能与触摸板双指滑轮功能冲突

### ISSUE THREAD

**Issue by alexcchen** [xianyukang/MyKeymap#133]
当使用“窗口管理”功能后，触摸板的双指滑动的滑轮功能将会失效，此时必须使用一次触摸板的三指滑动切换窗口功能，使用后，触摸板双指滑动的功能恢复。找了好久，一直以为是电脑驱动问题，中英文资料一顿查。然后使用按键重映射为文本“^!{tab}”替换原来的”窗口操作“-”窗口管理“功能，虽然上下左右键esdf可以用cap+esdf替换，麻烦一点点，不能接受无法使用x结束窗口，”窗口管理“功能和触摸板双指滑轮功能冲突这个问题有解决的可能性吗？

**Comment by alexcchen** [comment]
暂时可以用del键替换x键，突然的变换快捷键还是有些不适。略有遗憾，但还是感谢作者编写的优秀软件

**Comment by alexcchen** [comment]
虽然这么设置了，但是还是双指滚轮功能失效了，要被折磨疯了，双指缩放都好好的，唯独双指滑轮冷不丁突发性无症状的失效。可能不是这个原因。

**Comment by alexcchen** [comment]
用三指滑动也无法恢复双指滑轮功能

**Comment by alexcchen** [comment]
重启解决了，但是又试了下，使用“窗口管理”功能后，确实是会导致双指失效，是可以百分百复现的，至于为什么后来没使用“窗口管理”双指会导致失效的原因尚不清楚，双指缩放都是正常的

**Comment by alexcchen** [comment]
还有一个怀疑方向，可能是win10系统的iic通信的服务有问题，它会不会时不时的停止，看到一个帖子说，双指三指都失效，只剩下单指功能，后来重打上了iic协议的驱动后好了，不过他的是linnux系统

**Comment by xianyukang** [comment]
用默认配置能复现问题吗? 
我这边试了一下，并没有影响触摸板的滚轮功能

**Comment by alexcchen** [comment]
好的，我试下默认配置

**Comment by alexcchen** [comment]
MyKeymap-2.0-beta22
刚下的最新的版本，把cap+a重映射为“窗口朝族”-“窗口管理”，使用cap+a切换窗口后还是复现了双指滑轮无法使用的问题，三指切换窗口后恢复。这个就没办法了，毕竟这个问题挑电脑驱动和硬件，您的是操作正常的。

**Comment by xianyukang** [comment]
看其他用户有没有遇到，等待更多反馈，目前无从下手

**Comment by alexcchen** [comment]
https://github.com/xianyukang/MyKeymap/blob/main/bin/lib/KeymapManager.ahk
这个文件的第569行下面可以加一行
 this.RemapKey(space, "enter")
让窗口切换界面的空格键，变成enter键，因为我试了在窗口切换界面使用enter选择窗口后，双指滑轮功能是正常的，使用空格键后双指滑轮功能就失效了。

**Comment by xianyukang** [comment]
@alexcchen 
1. 我把 Remap 改成了 SendKey: https://github.com/xianyukang/MyKeymap/commit/8c6c93925ee8c657abbb7b390d229bb4545e8be5
2. 你重新下载这个文件，然后覆盖同名文件再试试?
https://github.com/xianyukang/MyKeymap/blob/main/bin/lib/KeymapManager.ahk
3. edsfx 这几个键都没问题，但只要按了空格键就会出问题，是这个意思吗?

**Comment by alexcchen** [comment]
替换成功，问题解决，感谢作者的付出，nice

**Comment by alexcchen** [comment]
是的，其键和enter键都没问题，唯独空格键会让双指失效，可能是触控面板的驱动程序在等待回车键按下，然后恢复双指滑动功能，现在替换后就修复了

**Comment by xianyukang** [comment]
解决了就好，又少了一个 bug，好耶 \(^o^)/~

**Comment by alexcchen** [comment]
后来还是断断续续的双指滑动失灵，又不好意思提，并且好几分钟双指滑轮都失效状态，没有恢复的方法，只能用着用着就恢复了，其他双指功能缩放和双指模拟右键都是正常的，好几天，一会就来一次失效，还必须几到十几分钟不等的失效，搞得头疼，实在不行就把双指的功能给关掉了，或者把mykeymap关掉，左右横跳的选择让人很不甘心，但又心心念念的触摸板滑轮和mykeymap都非常好用，试了好几百遍什么原因造成的，找不到结果，每次出现双指失灵立马停下手头工作，回想刚才按了啥键，停下来又是十几二十分钟的琢磨，人都搞得魔怔了，还下了keycastow来在屏幕上实时显示按键按了些啥，keyboard tracer来跟踪记录按键按了啥，终于在今天晚上的半小时前，可算是彻底找到原因并解决了，原因还是这个remap，和sendkey，的区别，先是想着失灵的情况基本是在输入excel的内容后，就容易发生双指滑轮失灵现象，于是打开excel输入文字，一两分钟就成功复现了双指滑动失灵现象，又搞了半小时，最后终于发现了使用CapsLock+desf来模拟上下左右的时候，因为输入文字的时候需要左右调整输入位置修改数字，容易大概率出现失灵的情况，接着疯狂按CapsLock+desf来模拟上下左右，就会9层的概率出现失灵的情况，按着按着又发现但是慢慢的把上下左右重新按两三遍，双指触摸滑动功能又恢复了，感觉看到了希望，即便这样，也总算是有解决的办法了，不用干巴巴的等它不确定的恢复时间，只用花上几秒按两遍上下左右就能恢复触摸板双指滑动的功能。接着我有想着去查看github的bin里面的，bin文件夹的mykeymap.ahk，看下关于CapsLock+desf是怎么写的，看不懂不会。又想着既然可以配置该按键的重映射，就去data文件夹的congfig.json查看capslock的desf是什么情况，看见capslock下的desf使用了"remapToKey":，顿时警觉，又看到还有些用的方法是sendtokey，于是打开设置页面，把capslock的desf从重映射按键变为了加了大括号的输入文本或按键，保存后，再去data文件夹里面的config.json查看，变成了"keysToSend":，再试着疯狂按CapsLock+defs快速的方向转换， 结果就触摸板双指滑动一直正常，然后激动着去设置里面把所有用到的“重映射按键”替换为了“输入文本或按键”再加个大括号，目前算是正常解决了双指滑动偶发性失效不确定性恢复的原因，我的电脑触摸板驱动跟remapToKey有仇，这个困扰一个多月，研究几十小时的触摸板双指失效问题，告一段落，完结撒花，特此记录，希望给有遇到同样触摸板双指失灵情况的伙伴能有所借鉴，也希望mykeymap作者能把按键重映射功能的remaptokey写成Keystosend

**Comment by xianyukang** [comment]
@alexcchen 
- 已经把所有的 remap 改成了 send: https://github.com/xianyukang/MyKeymap/commit/6f7eec2dfa15be4efdfacb7c5b8538249058294a
- 麻烦下载这个文件并覆盖同名文件，然后还原之前的案发现场，看看问题是否还会出现?
https://github.com/xianyukang/MyKeymap/blob/6f7eec2dfa15be4efdfacb7c5b8538249058294a/bin/lib/KeymapManager.ahk

**Comment by alexcchen** [comment]
替换后，测试正常，特意改回了使用“重映射按键”功能来来进行实验，没有出现触摸板双指滑动失灵现象，已经解决该问题，谢谢作者。
