### ISSUE TITLE
关于Capslock 命令的建议

### ISSUE THREAD

**Issue by EyoungShieh1992** [xianyukang/MyKeymap#134]
版本号：MyKeymap2.0-beta22
建议：能否在Capslock 命令的弹窗中，在输入错误的字符后，可以删除修改，匹配到指令后再执行

感谢大佬提供的软件

**Comment by xianyukang** [comment]
- 输错了可以按 Capslock 或 Esc 从头再来
- 删除字符属于可有可无的功能，个人没有动力去折腾和调试
