### ISSUE TITLE
无法通过拷贝data文件更新新版本

### ISSUE THREAD

**Issue by LDmoxeii** [xianyukang/MyKeymap#137]
在覆盖旧版本data文件后启动新版本应用出现报错
![屏幕截图 2023-12-12 162652](https://github.com/xianyukang/MyKeymap/assets/117140741/83cac3d5-0da3-40b9-a96e-93decb763dfe)
![屏幕截图 2023-12-12 162647](https://github.com/xianyukang/MyKeymap/assets/117140741/06d5591d-35e4-4abf-8f95-72ee7be49936)
![屏幕截图 2023-12-12 162637](https://github.com/xianyukang/MyKeymap/assets/117140741/226e4f2c-1e52-4e4a-8395-00b4004dd44d)
![屏幕截图 2023-12-12 162629](https://github.com/xianyukang/MyKeymap/assets/117140741/8d734de1-430f-45f2-b262-a7fd79caa6c0)
 并且在尝试手动配置是发现找不到之前的关于《模拟 Alt+Tab 热键》
 尝试使用!{tab}也无法实现该功能

**Comment by xianyukang** [comment]
1. 不能从 1.0 升级到 2.0，需要重配
2. 模拟 Alt+Tab 去掉了，因为可以用 Capslock + E 替代，对比 Alt+Tab 只是多按了一次空格键，当有很多窗口时还能用 EDSFX 切换或关闭窗口
