### ISSUE TITLE
不支持鼠标滚轮的热键

### ISSUE THREAD

**Issue by viocha** [xianyukang/MyKeymap#138]
我想重映射`Ctrl+向下滚动`这个热键，正确的语法为`^WheelDown`，但是软件显示错误
![image](https://github.com/xianyukang/MyKeymap/assets/66580331/a53edf11-58ec-47a1-972d-47132764eb6b)

**Comment by xianyukang** [comment]
奇怪，我这样配没遇到问题，你具体是怎么配的呢?
![image](https://github.com/xianyukang/MyKeymap/assets/24707226/0ed11121-0aa6-4459-9b9f-dcb7c0907315)

**Comment by viocha** [comment]
这样配置的
![image](https://github.com/xianyukang/MyKeymap/assets/66580331/93ef9670-65a1-4df9-a227-d9b7cbcf805f)

**Comment by xianyukang** [comment]
解决了，可以下载这个并覆盖同名文件，再像之前一样配置应该不会报错:
https://github.com/xianyukang/MyKeymap/blob/main/bin/lib/KeymapManager.ahk

**Comment by viocha** [comment]
> 解决了，可以下载这个并覆盖同名文件，再像之前一样配置应该不会报错: [`main`/bin/lib/KeymapManager.ahk](https://github.com/xianyukang/MyKeymap/blob/main/bin/lib/KeymapManager.ahk?rgh-link-date=2023-12-13T13%3A25%3A46Z)

自定义热键里面能映射成功，但在触发键模式里面依然存在修饰键不起作用的问题，比如这个Alt+Tab不起作用
![image](https://github.com/xianyukang/MyKeymap/assets/66580331/9fdf39d9-4450-4af3-97d0-9cafd1c5e75d)

**Comment by xianyukang** [comment]
用「 输入文本或按键 」可以解决，填 `!{tab}`

**Comment by viocha** [comment]
> 用「 输入文本或按键 」可以解决，填 `!{tab}`

好的，谢谢
