### ISSUE TITLE
[功能建议]希望自定义热键能支持分组

### ISSUE THREAD

**Issue by viocha** [xianyukang/MyKeymap#139]
希望自定义热键能像触发键模式那样支持创建命名的分组，用来区分不同的使用场景
![image](https://github.com/xianyukang/MyKeymap/assets/66580331/e3e01450-f393-4fa8-ac57-e4dbf7490d30)
还有一个疑问，在触发键模式里面，为什么不支持Ctrl, Alt这样的修饰键，就像Capslock+这样用于增强的功能
![image](https://github.com/xianyukang/MyKeymap/assets/66580331/09ae9831-0a9c-4d36-8fe3-6fe6e5c7a0fc)
![image](https://github.com/xianyukang/MyKeymap/assets/66580331/198e44aa-8e1b-41ba-a2a4-633be9ebf4c0)

**Comment by xianyukang** [comment]
capslock + LAlt + j 不是和
capslock + f + j 一个样吗? 你说不支持 LAlt 我认为这是误解

**Comment by xianyukang** [comment]
自定义热键的分组，有没有实际用例，现有的功能可以满足需求吗？

**Comment by viocha** [comment]
> 自定义热键的分组，有没有实际用例，现有的功能可以满足需求吗？

可能会针对不同的app定义他们的热键，在生效范围内指定app（默认是全局生效），然而这些不同app的热键又混杂在一起，不方便查找和修改

**Comment by viocha** [comment]
> capslock + LAlt + j 不是和 capslock + f + j 一个样吗? 你说不支持 LAlt 我认为这是误解

好的，明白了

**Comment by xianyukang** [comment]
可以试试这样配:
![image](https://github.com/xianyukang/MyKeymap/assets/24707226/34c54498-7905-4fe9-bd5d-014fc2a1de80)

**Comment by viocha** [comment]
> 可以试试这样配: ![image](https://private-user-images.githubusercontent.com/24707226/290503923-34c54498-7905-4fe9-bd5d-014fc2a1de80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MDI0NjUsIm5iZiI6MTcwMjgwMjE2NSwicGF0aCI6Ii8yNDcwNzIyNi8yOTA1MDM5MjMtMzRjNTQ0OTgtNzkwNS00ZmU5LWJkNWQtMDE0ZmMyYTFkZTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDA4MzYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhZmVjMDg2ODIzNGU2MjQxMWEwMGZhNjM5YjI2ZTlkMzRmY2E2MDQwYWM3ODUxYTNmNzA0OWQzYWU1OTE1NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tVVyb4eeTEc6wJ76YQqV65BnOaixMLWglk81yP0_Kno)

我不太喜欢用触发键功能，因为总要按住一个键才能使用。我常用的是自定义热键面板，建议对**自定义热键**界面进行改进，比如，设计成这种布局
![image](https://github.com/xianyukang/MyKeymap/assets/66580331/d5529852-9918-4955-8089-d8b4057076e2)

这是目前的布局：
![image](https://github.com/xianyukang/MyKeymap/assets/66580331/092edbea-2952-4a7f-8606-cfa516236574)

**Comment by viocha** [comment]
我认为针对使用场景和功能进行按键分类比针对按键组合的第一个键进行分类更加实用和灵活，所以希望能对**自定义热键界面**添加分类功能

**Comment by xianyukang** [comment]
用 alt 或 win 之类的热键，也要先按住一个键才能用。

你建议的布局也许更好，但暂未发现真实的/有吸引力的应用场景，所以暂时没有欲望/动力去做这件事。

**Comment by viocha** [comment]
> 用 alt 或 win 之类的热键，也要先按住一个键才能用。
> 
> 你建议的布局也许更好，但暂未发现真实的/有吸引力的应用场景，所以暂时没有欲望/动力去做这件事。


能否考虑一下在设置界面新增按键列表时能选择指定为自定义热键模式或者触发键模式
![image](https://github.com/xianyukang/MyKeymap/assets/66580331/6f769b6d-8113-4cfc-a6c1-cc01f3020f2f)

**Comment by xianyukang** [comment]
这么做有什么吸引力呢?

**Comment by viocha** [comment]
> 这么做有什么吸引力呢?

可以给自定义热键分组取名字，比如QQ自定义热键，Edge自定义热键，微信自定义热键，Notepad自定义热键，VSCode自定义热点。如果没有以上分组，这些热键就排列在一个分组里面，比如Notepad自定义了Ctrl W，VSCode也自定义了Ctrl W，Edge也自定义了Ctrl W，要找到VSCode自定义的Ctrl W，就得一个一个点开查看名称。

如果能创建自定义热键分组，还能创建这些分组，窗口切换自定义热键，光标移动自定义热键，启动应用自定义热键，文本插入自定义热键等等，也更方便管理。

**Comment by xianyukang** [comment]
- 自定义热键会这么麻烦是因为它用的少，例如 ctrl + w 会被 capslock + w 取代
- 在图中的位置点一下就能看到 notepad 中以 capslock 开头的热键，不用一个个点开
- 窗口切换、光标移动、启动应用等功能一般都是全局生效，无需分组
![image](https://github.com/xianyukang/MyKeymap/assets/24707226/5c8c8d0f-d607-408c-ace4-ac210001a8b6)


- 不理解为啥要排斥 capslock 这样的触发键，我认为定义 ctrl/alt/win 系的热键有两个缺点:
  - ctrl/win 不如 capslock 键好按
  - 容易和应用或系统自带的热键产生冲突，例如 alt + f 常常作为应用内热键

**Comment by viocha** [comment]
因为MyKeyMap的文本编辑内置函数太少了，没时间去自定义ahk函数，所以就直接用Capslock+了，用MyKeyMap主要是为了重映射热键
![image](https://github.com/xianyukang/MyKeymap/assets/66580331/f38b7b89-79c4-4b49-8a98-468efd414a5a)

**Comment by xianyukang** [comment]
- 我想到一个简单的优化办法，和分组差不多，这样能满足需求吗?
- 如果左边的备注如果为空，说明这个热键在选中的程序组中没有配置
![image](https://github.com/xianyukang/MyKeymap/assets/24707226/59250849-67d9-4236-be7d-6c42e2a7384e)
- 可以下载这个做测试: https://wwqw.lanzouj.com/ilvc31ickebc 密码 cqk8

**Comment by xianyukang** [comment]
capslock+ 的上移 3/5/10/30 次配一下也不难，例如上移 10 次是: `{up 10}`
我喜欢用 capslock 移动鼠标/滚轮，点击需要编辑的位置，这个做法通用性更好

**Comment by viocha** [comment]
谢谢，不用了，我想我可以把配置写在单独的文件中，然后通过脚本合并到软件的数据目录，配置文件yyds
