### ISSUE TITLE
J   K  一直按下，松开J选择文本模式与双拼按键冲突

### ISSUE THREAD

**Issue by hyb1989** [xianyukang/MyKeymap#14]
使用小鹤双拼，JK连用是很常见的，因为J是声母j，K是韵母ing ，这就导致了按钮冲突。

**Comment by xianyukang** [comment]
有其他方案吗?

因为  Shift+上/下/左/右/Home/End/Esc/Delete  是常用的组合键
另外  Ctrl +上/下/左/右/BackSpace/Tab        也是常用的组合键

所以有没有其他「 前置键 」像 「 J+K / J+L 」 一样方便 ?  
并且能把上述 14 个常用组合键都分配好

**Comment by hyb1989** [comment]
暂时没有想到很好的方案，所以不能给出更换组合键的建议。是否可以考虑可以

**Comment by hyb1989** [comment]
可以参考一下 HHKB 60键的布局规划。官方主打的码字利器，60键实现104键功能。

**Comment by xianyukang** [comment]
你能适应 J 模式,  但觉得 J+K 会影响打字,  是这个意思吗 ?
如果你的问题是这样,  我可以考虑把 J+K 改成 J+O,  因为连按 J+O 的概率比较小

如果你不能适应 J 模式,  直接把这个模式关闭就好了

**Comment by xianyukang** [comment]
刚刚想到了利用 9 和 0 两个键作为前置键,  说不定能解决 J 模式对打字的侵入性,  我试试方不方便

**Comment by xianyukang** [comment]
1. J 是最好按的前置键,  付出一些适应代价换 J 模式的便利性,  我认为是值得的
2. 如果不适应 J 模式,  在 1.0.28 版本中增加了逗号模式作为 J 模式的下位替代

**Comment by szzhiyang** [comment]
@hyb1989 [**Power Keys**](https://powerkeys.github.io/) 的 [**空格编辑**](https://powerkeys.github.io/space) 功能用空格键作为前置键，还不影响空格输入和输入法上屏，键位布局也更合理、舒适、易用、强大，就是你想要的。
