### ISSUE TITLE
J模式冲突

### ISSUE THREAD

**Issue by alexcchen** [xianyukang/MyKeymap#140]
当我打字的时候，开启了J模式，该模式触发延迟拉到400ms，
i是在J模式下分配的”输入文本或按键“{blind}{up}，n在J模式下无配置，用手速最快的方法输入“井”jin“这个拼音加“空格”，通过keycastow实时显示，我输入的确实是”jin空格“的顺序，但有9/31的概率会变成“ijn“，
我把J模式的i分配为”无配置“后，变成6/47的概率输入为”ijn“，
我把J模式下的i配置为“重映射按键”的up，6/68的概率输入为”ijn“，
我把J模式关闭后，出现“ijn”的概率为0，就正常了。
我怀疑处理判断是否开启J模式的代码判断完毕后发现不符合触发时间，吐出了j，但此时i已经捷足先登，输出来了，导致i比j先出现，可能提高J模式触发判断代码的运行效率可以解决该问题

**Comment by xianyukang** [comment]
- 我用我最快的手速按 ji 两个键，每次都是输出 ji，没出现 "ij" 这样的逆序输出
- 简单测了一下 J 键处理时间，都是 0~16 ms，应该不会有效率问题
- 如果觉得 J 方便且能接受缺点就用 J，否则推荐用句号键/逗号键/CapsLock 作为触发键

**Comment by alexcchen** [comment]
![ijing](https://github.com/xianyukang/MyKeymap/assets/41438765/c3d91cfa-0871-4e11-9144-798f5d9dff5a)
![image](https://github.com/xianyukang/MyKeymap/assets/41438765/e4596f06-6e51-437a-83d4-43720b6da9a9)
收到谢谢作者回复的解决方案，我测试是连续重复快速输入

**Comment by laoyaog** [comment]
延迟设置到100ms以内就不容易误触了
