### ISSUE TITLE
希望增加对某个程序的生效方式

### ISSUE THREAD

**Issue by ShigaHaruki** [xianyukang/MyKeymap#146]

**Comment by alexcchen** [comment]
现在这个软件是可以做到的你要求的功能的
步骤如下
1.打开软件设置界面
2.点击设置
![image](https://github.com/user-attachments/assets/427dbefd-6028-4403-bfaf-3df58cbd2346)
3.（language调成中文）点击右侧的编辑程序分组
![image](https://github.com/user-attachments/assets/b11643b7-c7bc-4a47-b915-21012a322f2f)
![image](https://github.com/user-attachments/assets/79e4312a-42bc-465c-9cae-4d459b2ec08f)
4.点击添加一行，写一个组名
![image](https://github.com/user-attachments/assets/a4b87aa2-5562-4db9-817d-8e03bedd1936)
5.点击添加一行左边相邻的查看窗口标识符，会弹出一个白色窗口，注意灰色框里的内容才是有用的
![image](https://github.com/user-attachments/assets/409ed44e-3206-4289-b302-f14778a58333)
6.打开你需要仅对此生效的某个软件，复制窗口标识符里灰色框里面带".exe"后缀的”ank_exe xxxx.exe“整行软件名字
![image](https://github.com/user-attachments/assets/271b46cc-a3e5-4530-bdbf-fbe33ad74c47)
7.回到设置页面，粘贴到你设置的组名的旁边的窗口标识符列里面（有多个软件需要设置时重复6和7步骤回车分行粘贴）
![image](https://github.com/user-attachments/assets/2655f585-c45c-464c-b980-7f415f91e59f)
8.点击添加一行按钮旁边的保存按钮，关闭悬浮的窗口标识选择软件
9.设置你需要的快捷键，然后选择全局生效改为你编辑的组名，保存后这个设置的按钮重映射功能就只对你刚才的选择的软件组生效
![image](https://github.com/user-attachments/assets/a12e5fe3-df05-4cef-95c3-18e9bed795ac)

**Comment by xianyukang** [comment]
可以在设置中「 编辑程序分组 」:
![image](https://github.com/user-attachments/assets/e0080478-76a7-4346-9a5c-562fb4dda855)
