### ISSUE TITLE
在WPS的WORD里，文字往左选、往右选失效

### ISSUE THREAD

**Issue by xiaohuihui522** [xianyukang/MyKeymap#147]
试过 在浏览器、Notepad很多地方均正常，但是WPS里使用就只有左右移的效果，没有实现选中的效果。
我使用的WPS版本是
![image](https://github.com/xianyukang/MyKeymap/assets/116368348/d205f550-fe5e-4413-aee6-5c2ad084b1ea)

微软的word没得试过是否正常。请大佬支支招

**Comment by xianyukang** [comment]
WPS 有 bug，它对 ahk 的支持不够友好
