### ISSUE TITLE
和其他软件发生冲突

### ISSUE THREAD

**Issue by eamon2003** [xianyukang/MyKeymap#149]
与quicker的轮盘功能发生冲突 经测试 无论轮盘设置用什么鼠标键触发均会导致ctrl+alt+‘’ 的快捷键变成ctrl+" 且会对ctrl键进行锁定并不可取消 我只设置了几个功能键
![image](https://github.com/xianyukang/MyKeymap/assets/51506762/76218acc-ed26-4b2c-958f-ae03c3043480)
![image](https://github.com/xianyukang/MyKeymap/assets/51506762/84fbb96a-cc82-461d-bf2f-dfcb37985a0d)

**Comment by xianyukang** [comment]
可以把 MyKeymap 的右 Alt 映射为 Ctrl 删掉
![Uploading image.png…]()
