### ISSUE TITLE
“窗口居中”兼容不同大小显示屏&添加非全局模式的建议

### ISSUE THREAD

**Issue by chenheyuu** [xianyukang/MyKeymap#15]
用过很多不同键盘映射功能，但又很难说Mykeymap仅仅是这类功能单一的工具，好用到心坎了，对于不熟悉编程的朋友来说，是非常有意义的。
咳咳，接下来，说说我的一些想法。

- 由于是15.6寸的笔记本，所以放大的整体的显示，如下：

操作中心-所有设置-系统-显示-缩放与布局-125%

也就导致“窗口居中”超出了屏幕一点，再缩小视图看起来又费劲，同时又很喜欢这个功能，嘿嘿。而我能想到解决办法：
**_能自定义调整相关参数（窗口大小）**_，如；
增加多些分辨率数值【960x640】、【720x480】······；
直接调整窗口大小的百分比（80%、70%、60%…）。

- 现在按键模式真的相当丰富了，但我个人最喜欢的还是“空格模式”，这与我（办公学习时，左手覆盖键盘左侧功能区、右手操控鼠标）操作模式有关。比如，在使用Adobe系列修图、剪辑、做PPT等等啦。然后就会产生非常多的快捷键、而且如果要保持手型的话都需要小拇指参与按功能键，空格键是无法在任何应用参与快捷键的定义，这个地理位置绝佳的位置就只能这样了吗🐴
- 说起“Mykeymap”空格模式的优势，就是打字的手型不用变化，按起来的相当的轻松，不会很刻意，用起来也不会冲突。紧接着，我就不够用了（去掉）为平衡因快捷键而产生的问题，我经历的一下心路历程：
- 将矛盾转移到鼠标，鼠标手势多了曲线和折线也加大了使用成本。quicker似乎是个不错的选择，那样的话右手也太忙了不是吗，得得得，这也不行那也不行，我还是换个专用的键盘、要么在鼠标上镶个键盘哈哈。

**如果“Mykeymap”能区分“全局”和“某一应用”**如wgesture，对于这样一类工作人群来说，设置快捷键的自由度肯定是更高的，比如我，在就会在某应用里设置“Ctrl+shift+alt+C=空格键+C ",采用类似的思路，用空格键替换所有的需要Ctrl、Alt这类功能键，或者简化常用快捷键。达到不移动左手或右手 手掌、减轻小拇指的压力目的。

这听起来有点像B站有人提到的 Power key，但它无法自定义，依旧没有全局与应用的区分

**Comment by xianyukang** [comment]
好的,  以后会增加分应用的配置

**Comment by chenheyuu** [comment]
很开心，嘻嘻

**Comment by xianyukang** [comment]
1.0.28 版本增加了「 分应用配置 」,  感兴趣可以试试 ^_^

**Comment by chenheyuu** [comment]
试过了呦，「 分应用配置 」很好用，非常感谢 ^_^
