### ISSUE TITLE
2.0.0-beta25版本中SinglePress若配置为 [输入文本] 功能则无法工作

### ISSUE THREAD

**Issue by KagaJiankui** [xianyukang/MyKeymap#152]
在2.0.0-beta25中将Capslock模式 (*capslock触发) 下单击CapsLock的映射配置为SinglePress后, 如果重启资源管理器, 该映射导致按下CapsLock键无任何反应. 将这个模式配置为文字编辑功能或其他功能时仍然工作正常.

**Comment by xianyukang** [comment]
具体怎么配的，发一下截图?

**Comment by KagaJiankui** [comment]
(现在回退到1.2.7版本后暂时正常)

这是在2.0.0-beta25版本的配置:
![image](https://github.com/xianyukang/MyKeymap/assets/58453886/2d39a684-af48-4794-aa13-3af13ecd037c)

同一个配置在1.2.5, 1.2.7版本均可正常工作. 并且, 在2.0.0-beta25版本下**输入文本或按键**配置为输入其他文本或按键也无法正常工作, 按CapsLock无任何反应.

**Comment by KagaJiankui** [comment]
补充: 有时还会出现在**自定义热键**中配置alt+CapsLock切换CapsLock状态后, 连续按alt+CapsLock只会开启CapsLock而无法关闭CapsLock的bug, 需要间隔1s以上再按才能关闭

**Comment by xianyukang** [comment]
怀疑和 `#{space}` 有关，
试试把 `#{space}` 改成 `abc` 再测试一下?

**Comment by KagaJiankui** [comment]
之前用abc这种纯字符串测试也是同样的结果, 没有任何反应

**Comment by KagaJiankui** [comment]
怀疑可能是放在C:\Program Files或者C:\ProgramData下导致的, 放在用户目录下就没有问题

**Comment by xianyukang** [comment]
额，可能被安全管家拦截了? 
我记得 360 会屏蔽掉 ahk 发送的模拟按键，需要把软件添加到白名单才行

**Comment by KagaJiankui** [comment]
目前使用的火绒安全软件, 已经将整个目录和关键可执行文件都加入白名单, 自定义规则也不影响

**Comment by KagaJiankui** [comment]
大概定位到原因了, 重置为104键的键盘布局后会导致singlepress失效
