### ISSUE TITLE
新版不支持launch_multiple了吗？

### ISSUE THREAD

**Issue by AlfredHuangZP** [xianyukang/MyKeymap#153]
内置函数里是不支持launch_multiple同时打开多个程序和网页了吗，感觉挺好用的。新版不知道如何实现以前的效果

**Comment by xianyukang** [comment]
换了个名字，可以用 `LaunchMultiple("https://baidu.com", "https://google.com")`

**Comment by AlfredHuangZP** [comment]
> 换了个名字，可以用 `LaunchMultiple("https://baidu.com", "https://google.com")`

感谢回复，是我没看到“变量方法的差别”说明，我的问题。
另外非常感谢作者，这个软件实在是太棒了！！！用了很久了，戒不掉了。
