### ISSUE TITLE
请问MyKeymap的程式MyKeymap-2.0-beta25.7z，可以放到 github  上吗

### ISSUE THREAD

**Issue by trevim99** [xianyukang/MyKeymap#154]
我看了网站跟b站的 MyKeymap 介绍，一看就有惊绝的感觉。
感觉是很精心的思考过键盘的各键位配置。谢谢您的介绍及分享。

请问MyKeymap的程式MyKeymap-2.0-beta25.7z，可以放到 github  上吗?
我用网站的连接想下载MyKeymap-2.0-beta25.7z，因为在海外，下载了好几次都无法成功，谢谢您

(https://wwqw.lanzouj.com/iB5YV1i034cj ，在海外，无法下载)

**Comment by xianyukang** [comment]
刚刚添加了 release，快试试
