### ISSUE TITLE
搜狗输入法使用sendinput 模式发送按键，输出内容不一致

### ISSUE THREAD

**Issue by Jastmaskerrr** [xianyukang/MyKeymap#155]
在sendinput 模式下，例如在【缩写】设置为按下‘’qq‘’，输出123456789
但实际输出为与期望输出不同，会有几个数字不同。
而使用sendevent正常。

在微软输入法中一切正常。搜狗输入法10.3版本和9.7b版本都有问题
了解说明中的可能有 兼容问题，但是否有 解决办法

**Comment by xianyukang** [comment]
用 sendevent 也行啊
