### ISSUE TITLE
关闭音量管理器时导致的capslock键失效

### ISSUE THREAD

**Issue by Alddp** [xianyukang/MyKeymap#159]
按capslock+c后再用capslock+c关闭时多按一次c后单按capslock不会弹出命令框而是切换大小写

**Comment by Alddp** [comment]
如果在看B站全屏，用c关闭的话会键入一个esc退出全屏

**Comment by xianyukang** [comment]
> 如果在看B站全屏，用c关闭的话会键入一个esc退出全屏

刚刚修复了，试试下载 beta28 版本

**Comment by Alddp** [comment]
beta28版本的音量管理器按c也关不了，要先点一下桌面才能关，然后调节音量的功能也失效了，我重新开关一分钟作用才恢复正常，然后关闭mykeymap再打开又那样了

**Comment by xianyukang** [comment]
重启电脑问题还会出现吗? 建议录个 gif，然后描述一下复现步骤
