### ISSUE TITLE
窗口操作添加窗口置顶功能

### ISSUE THREAD

**Issue by qijizh** [xianyukang/MyKeymap#16]
看文档的时候，特别希望有个窗口置顶

**Comment by xianyukang** [comment]
如图,  窗口操作有置顶功能,  ~~也可以花 900 块试试搞个双显示器~~

![image](https://user-images.githubusercontent.com/24707226/146664006-e9258674-401b-43f3-b8e9-316616a25b97.png)

**Comment by qijizh** [comment]
抱歉，我的表达可能有误。就是指定窗口指定后，就像贴图一样在最上层，即使不是主程序
