### ISSUE TITLE
建议新增导出功能,方便在不同的设备享受同一套配置,不需要重新设置

### ISSUE THREAD

**Issue by Lovi-github** [xianyukang/MyKeymap#161]
也就是导出那一套配置之后,右键mykeymap的哪个小图标显示导入/导出,选择导入,选择配置,即可和前一台电脑配置的一模一样

**Comment by xianyukang** [comment]
- 因为是绿色软件，直接把 MyKeymap 整个文件夹复制到另一台电脑就能用
- 如果想备份，配置文件是 MyKeyamp 文件夹里的 `data\config.json`
