### ISSUE TITLE
BUG:win7系统不能正常启动

### ISSUE THREAD

**Issue by Lovi-github** [xianyukang/MyKeymap#162]
应该是SetThreadDpiAwarenessContext的原因,具体不知道怎么改,不知道有没有简单的方法兼容win7(公司的工作电脑win7的...)

![image](https://github.com/xianyukang/MyKeymap/assets/96587251/2fb9c7b6-f2c6-4b6e-93d3-b31bdb0993fa)

**Comment by xianyukang** [comment]
- 找到对应文件，然后删掉这个调用呗，它是用来处理屏幕 DPI 缩放的
- 另外 Win7 可以用旧版，1.0.28

**Comment by wuhao1477** [comment]
> * 找到对应文件，然后删掉这个调用呗，它是用来处理屏幕 DPI 缩放的
> * 另外 Win7 可以用旧版，1.0.28

请问一下旧版本1.0.28 在哪下载呢？

**Comment by xianyukang** [comment]
> > * 找到对应文件，然后删掉这个调用呗，它是用来处理屏幕 DPI 缩放的
> > * 另外 Win7 可以用旧版，1.0.28
> 
> 请问一下旧版本1.0.28 在哪下载呢？

这个页面里有下载链接: https://xianyukang.com/MyKeymap-Change-Log.html
