### ISSUE TITLE
請問MyKeyMap如何叫出emoji視窗

### ISSUE THREAD

**Issue by trevim99** [xianyukang/MyKeymap#166]
您好

謝謝開發這麼好的MyKeyMap

一、因為 windows 的 emoji 視窗 (Win鍵+點) 很難按
請問在MyKeyMap建議怎麼設定，才會方便好按？

我如果想在 J模式中設定 (J模式J鍵)+Q 鍵是 Win鍵+點鍵(emoji)，請問要怎麼設定？謝謝

二、我有一些常用的檔案，放在電腦的不同資料夾中
例如 
autohotkeyHelp.chm  (幫助檔)
example.xls (excel)
等等的

請問在MyKeyMap 建議如何設定，才可以快速召喚？

謝謝您

**Comment by xianyukang** [comment]
(1) 这样配能打开 Emoji 窗口
![image](https://github.com/xianyukang/MyKeymap/assets/24707226/8099ab76-a534-45d1-8fd8-8ecf53211714)

(2) 这样配能打开常用文件
![image](https://github.com/xianyukang/MyKeymap/assets/24707226/51db3614-a62f-4663-a77a-2bfca05dce1f)

**Comment by trevim99** [comment]
謝謝您，設定完成。有您真好!😁
