### ISSUE TITLE
請問更改全局快捷鍵

### ISSUE THREAD

**Issue by trevim99** [xianyukang/MyKeymap#167]
您好

請問如果有其他的應用程式把 F1 鍵設成全局快捷鍵，例如截圖程式 snipaste.exe把 F1 設成 截圖。 我希望在 vscode 中按 F1 恢復成 vscode  的默認功能 help ，而不是 截圖。

請問在 mykeymap 要怎麼設定? 謝謝

**Comment by winlans** [comment]
@trevim99 通过自定义热键（Custom Hotkeys） ，设定全局和软件分组，就可以实现你说的这种了

**Comment by trevim99** [comment]
大佬， 我再試試， 謝謝您😁😁😁
