### ISSUE TITLE
【功能需要】a模式

### ISSUE THREAD

**Issue by daisjj** [xianyukang/MyKeymap#168]
a作为前置键，很好按，应该很好用吧

**Comment by xianyukang** [comment]
可以自己配出来的吧, 打开设置琢磨一下?
![image](https://github.com/xianyukang/MyKeymap/assets/24707226/31d41061-673e-4b3e-b5f7-eb6189cfc64a)

**Comment by trevim99** [comment]
（我亂入一下）

看了阿康大佬的貼圖， 我好像懂了， 例如把f模示的觸發鍵f改爲a， 就是 a 模式 

謝謝阿康大佬🙏🙏🙏
