### ISSUE TITLE
希望增加应用程序规则

### ISSUE THREAD

**Issue by owwkmidream** [xianyukang/MyKeymap#17]
比如某程序运行时暂停，此类功能。在某些场景下不希望使用keymap，但总有忘记的时候，这时觉得如果有应用程序规则就好了。麻烦作者了。

**Comment by cloversky** [comment]
希望增加以下3个功能，1.增加导入导出功能，即使换一台电脑也可以快速导入配置文件进行工作，不用重新设置案件。2增加恢复默认设置功能。防止同一个功能设置相同的快捷键。3增加清除所有按键功能。可以按照自己的用键习惯进行设置，避免不常用的快捷键删除比较繁琐

**Comment by alexcchen** [comment]
将需要导出的配置文件从它目录的data文件夹的文件内容，复制到另一个mykemap的data文件里面覆盖后，配置就导入到另一台电脑里面了
设置快捷键命令
alt+’
可以将它设置为暂停/开启mykeymap的按键功能。

**Comment by xianyukang** [comment]
在 beta31 加上了应用程序规则，打开设置点击「 编辑程序分组 」然后修改「 Exclude 」组就好

**Comment by owwkmidream** [comment]
没想到还有closed的一天！之前正是因为这点弃用了，今天下回来试试
