### ISSUE TITLE
分号模式可否使用Alt+；触发并锁定？为什么在不锁定当前模式的前提下，全局“输入按键或文本”无论按哪个键都是重复第一个键的内容？

### ISSUE THREAD

**Issue by laoyaog** [xianyukang/MyKeymap#172]
1、电脑别人会用，若按；直接进入锁定状态别人可能会很迷惑，可否用一个修饰键（比如左Alt）+；进入和退出；模式的锁定状态？如何操作？
2、在不锁定当前模式的情况下（比如f模式不锁定），其他按键改为全局“输入按键或文本”，例如J设为{blind}，k设为{blind}。（中文的逗号和句号），在按下f键后按j在中文输入法情况下会输入中文逗号，在英文输入法情况下会输入英文逗号，但无论f键松开与否继续按k键，仍旧输入逗号而不是句号，这是什么原因？有什么办法解决吗？
谢谢

**Comment by xianyukang** [comment]
1. 可以用「 分号+空格 」锁定分号模式，一般人别不会误触这个热键
2. 检查一下配置，是不是配错了? 可以把输入句号改成输入 abc 看看效果

**Comment by laoyaog** [comment]
1.第一个问题已经解决，；+空格锁定很好用。
2.第二个问题尚未解决。
在不锁定当前模式的前提下：
（1）输入改为abc等单个字符没有出现任何问题，“要输入的按键或文本”里面应该填入{blind}{a}格式，这样不会影响按住shift后切换大小写，如果只设置输入为a而不加{}的话，会出现无法用shift切换大小写问题。
（2）逗号句号等标点问题仍旧存在，无论继续按哪个已经配置了任何标点符号的键，只会输入第一个标点符号（已测试键盘上所有标点符号，均是此情况）。
3.f模式不锁定的情况下输入标点符号其实更适合文字工作者，我平常用的标点符号主要就几种，比如逗号、句号、顿号、括号、感叹号和六角括号等和文字相关的，其他符号一般用不上，如果用；+空格模式的话还需要来回切换模式，反倒增加了操作量，如果用f模式不锁定直接输入标点符号就很快。
多谢解答！

**Comment by xianyukang** [comment]
其实我完全没听懂第二个问题是什么意思，建议重新下载 MyKeymap，然后把问题复现，最后发一下复现步骤

**Comment by laoyaog** [comment]
找到原因和解决方法了。
一、第二个问题的实际需求
1.短按分号键输出分号，按shift+短按分号输出冒号，和键盘原来功能一样（把singlepress设定为{blind};即可，}后面为英文分号）。
2.长按分号键+其他键，输出自定义的符号。
3.按分号+空格，进入缩写模式（把space设定为mykeymap相关-触发Abbreviation）。
二、出现的问题
长按分号+其他自定义为中文标点符号的，。、键，例如设定J为中文逗号，K为中文句号，当长按分号和J的时候，会输出中文逗号（前提是中文模式，如果英文模式会输出英文逗号），然后会出现以下两种情况：
1.持续按住分号不松手，松开J按下K，正常应该输出中文句号，但实际输出为J按键自定义的逗号。
2.全部松开按键，长按分号+k，正常应该输出中文句号，但实际输出仍旧为J按键自定义的逗号。
三、问题的原因
自定义J和K等键时，内容写成了{blind}，和{blind}。（逗号和句号为中文）。
四、解决方法
自定义按键内容应该写成英文符号的逗号和句号。
五、自定义按键内容加不加{blind}的区别
1.不加{blind}时，长按分号+长按shift+按J会在中文逗号和英文逗号之间轮换输出。
2.加{blind}时，长按分号+长按shift+按J，会输出左书名号，比较符合以前使用键盘的习惯（不会把逗号键的功能拆分为两个按键去实现，且左shift比较好按，而且这样可以省下一个自定义按键的位置）。

**Comment by laoyaog** [comment]
为啥评论会有两个3和空行
