### ISSUE TITLE
[BUG] 版本：2.0-beta29。在J模式-L按键绑定-Ctrl键：明明已经绑定了Ctrl键但使用不了Ctrl+C、V，B等功能。J模式下的-K键-Shift可以正常使用

### ISSUE THREAD

**Issue by shalimujiang** [xianyukang/MyKeymap#174]
## BUG内容如标题所说
![Clip_2024-07-28_11-48-03](https://github.com/user-attachments/assets/0bb76191-15ff-4f80-b5e6-ef917d80a2cd)
## 保存配置后操作
1. 在TXT文档中
2. 按下J键然后按下K键（J键松开），再通过S,D,F键来选文本。[**通过Shift按键来选本**] 文本编辑操作
3. 然后按下J键再按下L键（J键松开）再按C键（操作相当于：Ctrl+C复制文本）。[**通过Ctrl+C按键来复制文本**] 文本编辑操作
4. **最后的结果**是刚刚选的文本被删除了，应该是J模式下的C键功能冲突。
## GIF动图操作显示如下：
![recording](https://github.com/user-attachments/assets/e47498d7-0113-4169-b323-3a395dad9194)

**Comment by xianyukang** [comment]
- 这个不算 bug，就是这样设计的
- 因为 J 模式依旧是激活状态，所以 C 键是 Backspace 键

**Comment by shalimujiang** [comment]
那我应该怎么去设置比较好呢？

> * 这个不算 bug，就是这样设计的
> * 因为 J 模式依旧是激活状态，所以 C 键是 Backspace 键

那我应该怎么去设置比较好呢？

**Comment by shalimujiang** [comment]
因为我看到Shift功能可以用，所以想的Ctrl也可以使用

**Comment by xianyukang** [comment]
试试用 J + O 输入 Ctrl + C
![image](https://github.com/user-attachments/assets/f6626028-e0d4-4162-89be-5289dfdbf7b4)

**Comment by shalimujiang** [comment]
> 试试用 J + O 输入 Ctrl + C ![image](https://private-user-images.githubusercontent.com/24707226/352799751-f6626028-e0d4-4162-89be-5289dfdbf7b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNTY0NDEsIm5iZiI6MTcyMjE1NjE0MSwicGF0aCI6Ii8yNDcwNzIyNi8zNTI3OTk3NTEtZjY2MjYwMjgtZTBkNC00MTYyLTg5YmUtNTI4OWRmZGJmN2I0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDA4NDIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNDQ1MjYxMzM5YTNlZDRkZTZhOWQzZWMxMTI0MjBiYmU1ZTk0MjBjNjIxMDMwN2VkNTgwZjViMTFlN2NmMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._zDED3M12bZyY8zhmXHH-txLqtT68jfp17J-pSVou3Y)

感谢回复，谢谢。辛苦了

**Comment by shalimujiang** [comment]
> 试试用 J + O 输入 Ctrl + C ![image](https://private-user-images.githubusercontent.com/24707226/352799751-f6626028-e0d4-4162-89be-5289dfdbf7b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNTY0NDEsIm5iZiI6MTcyMjE1NjE0MSwicGF0aCI6Ii8yNDcwNzIyNi8zNTI3OTk3NTEtZjY2MjYwMjgtZTBkNC00MTYyLTg5YmUtNTI4OWRmZGJmN2I0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDA4NDIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNDQ1MjYxMzM5YTNlZDRkZTZhOWQzZWMxMTI0MjBiYmU1ZTk0MjBjNjIxMDMwN2VkNTgwZjViMTFlN2NmMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._zDED3M12bZyY8zhmXHH-txLqtT68jfp17J-pSVou3Y)

今年刚毕业，12月底会充电支持您。前两个月的工资给父母花
![Clip_2024-07-28_16-43-58](https://github.com/user-attachments/assets/a70ffa38-d468-417b-bcb8-7ebe8919be6d)
