### ISSUE TITLE
触发键有上层的时候，设置的延时无法生效。

### ISSUE THREAD

**Issue by wuqy1234** [xianyukang/MyKeymap#178]
![QQ截图20240819204602](https://github.com/user-attachments/assets/f8d6bd98-bc6e-4ae9-a741-928ad4ccfc75)
套了一层后，设定延时
![QQ截图20240819204408](https://github.com/user-attachments/assets/318fc637-6d76-4b1b-8372-7f1d78055856)
在主文件中无法写入延时
![QQ截图20240819204349](https://github.com/user-attachments/assets/ddf3d3ad-0faf-41ef-aa95-99b300ff64b7)

**Comment by xianyukang** [comment]
给第一层触发键加延时可以减少打字误触，
为啥要给第二层触发键设置延时? 我认为这没意义

**Comment by wuqy1234** [comment]
试想一下，想复用好用的J键和F键，J和F中的触发键都用了，我想复用J和F键，在写代码的时候用一套方案，在文字编辑的时候用一套方案，把F1-F12定为上层，那么就能使用12套方案的J键和F键了。

**Comment by xianyukang** [comment]
这和「触发延时」有啥关系?

**Comment by wuqy1234** [comment]
比如开启了F1代码编辑模式（我使用的是Tab开启代码编辑），在这个模式下，延时无法生效，Tab为上层的时候，J为按压键，K为J的触发键，由于没有延时，在打字的时候容易误触。

**Comment by wuqy1234** [comment]
我一直开启者Tab模式，，在Tab模式下，Tab为上层，下层所有的按压键（比如J键）都没有延时，按住J，单击K，触发操作。在打字的时候，打快了，就容易触发操作，而不是输入J和K。

**Comment by wuqy1234** [comment]
[config.json](https://github.com/user-attachments/files/16660941/config.json)

**Comment by xianyukang** [comment]
用这个文件覆盖 bin\settings.exe 试试?
https://wwqw.lanzouj.com/ih7AR27vhztc
密码:98p1

**Comment by wuqy1234** [comment]
在第一层（Space）没有使用“锁定当前模式（免去按住触发键）”时，第二层（空格+J键）设置了延时触发，那么第二层（空格+J键）无法生效（无法触发）。

**Comment by xianyukang** [comment]
我配了个 `空格+j+f` 做测试，能生效啊

**Comment by wuqy1234** [comment]
只要上一层（第一层）没有使用“锁定当前模式（免去按住触发键）”，那么第二层使用了延时，那么第二层就无法触发。比如Tab为上一层时，上一层没有使用锁定当前模式，“Tab+J代码编辑”设置了延时，那么“Tab+J代码编辑”就无法使用。除非Tab为上一层时，使用了“锁定当前模式”，“Tab+J代码编辑”，即使设置了延时，也能使用，同时“Tab+J代码编辑”的延时有效，即锁定Tab时，按J时，延时有效。

**Comment by xianyukang** [comment]
我怀疑是键盘的问题，你的键盘支持全键无冲吗?

**Comment by xianyukang** [comment]
可以把配置文件发我，然后说一下复现步骤

**Comment by wuqy1234** [comment]
谢谢你，你是对的，我的键盘不是全键无冲的。

**Comment by wuqy1234** [comment]
https://7072-prod-8gcmr08s23190b5f-1326387808.tcb.qcloud.la/custom_functions.ahk?sign=3406b2aa83dbf5e61117b6fff3b161df&t=1724153349
https://7072-prod-8gcmr08s23190b5f-1326387808.tcb.qcloud.la/QQ2024820-191824.mp4?sign=78434ef5a2935bfb3e8625e232b90191&t=1724153381
[Uploading config.json…]()

以上是我自定义的函数和演示视频。

**Comment by wuqy1234** [comment]
[config.json](https://github.com/user-attachments/files/16675048/config.json)

**Comment by xianyukang** [comment]
> https://7072-prod-8gcmr08s23190b5f-1326387808.tcb.qcloud.la/custom_functions.ahk?sign=3406b2aa83dbf5e61117b6fff3b161df&t=1724153349 https://7072-prod-8gcmr08s23190b5f-1326387808.tcb.qcloud.la/QQ2024820-191824.mp4?sign=78434ef5a2935bfb3e8625e232b90191&t=1724153381 Uploading config.json…
> 
> 以上是我自定义的函数和演示视频。

也可以试试 vscode 的自带缩写功能 `custom emmet snippets`
