### ISSUE TITLE
caps+C呼出的音量窗口并不在最前

### ISSUE THREAD

**Issue by Phoenix-balabala** [xianyukang/MyKeymap#179]
有时，caps+C呼出的音量窗口并不在最前，导致我按的edsf没有反应，必须鼠标点一下才能使用。该情况已经出现在微信浏览器游戏酷狗，但有时候又没有这个问题，很奇怪

**Comment by xianyukang** [comment]
- 这是 Windows 的系统限制，弹出的窗口不总能获取键盘焦点
- 试试改用这种启动方式，能否降低问题出现的概率?
- 但这种方式要用 `alt+tab` 代替 `C` 键，否则键盘焦点不会恢复
![image](https://github.com/user-attachments/assets/f38485f1-5297-4521-b9d4-89e333be031a)

**Comment by xianyukang** [comment]
试试用压缩包里的文件覆盖这两个:
- bin\SoundControl.exe
- bin\lib\Actions.ahk
> https://wwqw.lanzouj.com/iMAnh29e5xdc
> 密码:covb
