### ISSUE TITLE
热字串只有前3个能成功执行，后面所有的热字串都不能执行。反反复复测试了好多遍，还是不行。如果使用AutoHotkey64.exe运行，热字串都能有效执行，除了发送时间的"]d"外。

### ISSUE THREAD

**Issue by wuqy1234** [xianyukang/MyKeymap#180]
#HotIf 
::hello::
{
    MsgBox '你好，世界.'
}
:*:]d:: 
{
    Send FormatTime(, "yyyy/M/d h:mm tt") 
}
::china::你好中国
:*:dog::汪汪汪
:*:cat::喵喵喵 
::test::测试 
#HotIf

**Comment by xianyukang** [comment]
把这些热字串放到一个独立的 .ahk 脚本，
然后用独立的 AutoHotkey64.exe 进程运行，
总之别和 mykeymap 混合在同一个进程，怎么样? ( 这样能减少代码的互相影响 )

我试了下没问题，测试方法为:
1. 先输入空格
2. 输入任意热字串
3. 再输入空格

**Comment by wuqy1234** [comment]
谢谢你的指导，按照你的方法，都成功稳定执行了。
ActivateOrRun("", "D:\桌面临时文件\仓库\MyKeymap-2.0-beta29\MyKeymap-2.0-beta29\bin\AutoHotkey64.exe", "D:\桌面临时文件\仓库\MyKeymap-2.0-beta29\MyKeymap-2.0-beta29\data\HotString.ahk", "", false, false, false)
