### ISSUE TITLE
可否增加在系统托盘栏隐藏图标功能？

### ISSUE THREAD

**Issue by laoyaog** [xianyukang/MyKeymap#181]
试了几个托盘图标隐藏软件，都不太好用，可否增加为内置功能？在设置里面增加个选项？

**Comment by xianyukang** [comment]
收纳到这里面不就看不到了吗?

**Comment by laoyaog** [comment]
因为工作要求，需要彻底隐藏。
我在b站看了个帖子 https://www.bilibili.com/read/cv27693381/
按他方法实在弄不好，所以找作者大大求救来了。
很多效率工具都有这个功能，更有厉害点的任务管理器里的进程都是隐藏的，这个功能对部分人来说的确是刚需。
建议在设置里增加个 是否在托盘显示 的选择按钮，比如我常用的ditto，mouseinc里面都有这个选项。

**Comment by xianyukang** [comment]
你是想隐藏 MyKeymap 的托盘图标对吗?

**Comment by laoyaog** [comment]
对的

**Comment by xianyukang** [comment]
这个可以往 `data\custom_functions.ahk` 文件加一行代码:
A_IconHidden := true
然后重启 MyKeymap 就能看到效果
![image](https://github.com/user-attachments/assets/d89003fd-6f80-4823-b062-f1abeb339202)
