### ISSUE TITLE
识别活动窗口，打开windows文件管理器程序所在的目录

### ISSUE THREAD

**Issue by Jackysci** [xianyukang/MyKeymap#184]
希望加一个功能，如当正在使用chrome浏览器，按下按键，可以自动打开Chrome浏览器的文件目录，同样的其他软件，文件等也支持

**Comment by alexcchen** [comment]
是个好功能，偶尔能用到，每次都ctr+shift+esc打开进程浏览器，按名称排序后找下程序的进程名，再右键打开文件夹所在位置很是繁琐。如果一键快捷功能打开当前激活软件得文件夹所在位置，就是用得不多会老是忘记快捷键。

**Comment by Jackysci** [comment]
感谢大佬给出建议，平时用的更多的是utools，设置快捷键如双击alt后会呼出工具栏，里面内置了很多插件，比如内置了everything的功能，官方叫搜索，输入ss，就可以快速打开搜索功能，相当于使用内置的everything搜索本机文件，速度也很快，平时搜索也会用到您讲的那种方式，搜索文件名.exe等，但是像用到了MyKeymap就想能够再极速一点，原来也用了一些软件能直接打开软件所在目录，好像叫Nine，或者后面的一些，但是内容太专一或者太大，可能不同的习惯需要安装打开一堆小软件，使用了MyKeymap，就卸载了好多功能可以背替代的软件，但是提到上面的功能，自己去研究了一下ak语言，又尝试性写+Ai搜索，最终发现好像挺难的，也不太懂，总之，有可能的话，希望官方能做出来这样的功能，感谢
