### ISSUE TITLE
两份文档分屏模式查看时，滚动bug？

### ISSUE THREAD

**Issue by Phoenix-balabala** [xianyukang/MyKeymap#185]
我屏幕左边看pdf，右边看word
此时我使用Caps+U或O来滚动其中一个窗口，可行
但是如果alt+tab切换到另一个窗口，并也开始如上述滚动，则仍然会滚动之前的窗口，而不是切换到的这个
系统是win11，并不确定是不是windows的问题

另外如果我用alt+tab以及win+左或右来组合分屏，则caps+U或O滚动两个窗口都没反应

装了之前反馈Caps+C有时无法正常运行时给的补丁，也并不确定是不是补丁的问题

**Comment by Phoenix-balabala** [comment]
#179的那个

**Comment by xianyukang** [comment]
和鼠标位置有关系吗? 比如把鼠标移动到要滚动的窗口
![image](https://github.com/user-attachments/assets/8813c114-6728-408d-9f57-caedbea43640)

**Comment by Phoenix-balabala** [comment]
确实我试了一下，只有当鼠标箭头停在要滚动的窗口上方时，才能对其滚动

**Comment by Phoenix-balabala** [comment]
> 和鼠标位置有关系吗? 比如把鼠标移动到要滚动的窗口 ![image](https://private-user-images.githubusercontent.com/24707226/367362768-8813c114-6728-408d-9f57-caedbea43640.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNzUxNDQsIm5iZiI6MTcyNjI3NDg0NCwicGF0aCI6Ii8yNDcwNzIyNi8zNjczNjI3NjgtODgxM2MxMTQtNjcyOC00MDhkLTlmNTctY2FlZGJlYTQzNjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDAwNDcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxNzEyZWU2NzA1ZTc1MjhmOGE5MGM5YmQ1ZTY0MWY0OGQ5YWRlZjcyNzczYTZlOTAwMzEwY2QwNzdlODY1NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rckwXaOBXb-jN4c4vt-uPzf0F59K0ERJ1degNxH8GRw)

确实我试了一下，只有当鼠标箭头停在要滚动的窗口上方时，才能对其滚动
