### ISSUE TITLE
同时按住caps lock 和 space 会触发bug弹窗

### ISSUE THREAD

**Issue by SgAriFool** [xianyukang/MyKeymap#186]
在使用caps lock加上jk等方向键之后, mykeymap会自动进入一个锁定的模式, 需要按space退出, 但是如果此时不小心同时按住了caps lock 和 space, 就会发生bug弹窗
具体弹窗如下图: 
![image](https://github.com/user-attachments/assets/ead59644-0513-4a90-abba-754a9920d2ed)
需要重启才可以恢复正常

**Comment by xianyukang** [comment]
用的什么版本? 这个问题影响使用吗? ( 不影响就不管了 )
可以把配置文件也发一下，我试试能不能复现 ( 使用默认配置无法复现 )

**Comment by SgAriFool** [comment]
[config.json](https://github.com/user-attachments/files/17128037/config.json)
刚刚附件好像没发出来

**Comment by xianyukang** [comment]
奇怪，用了你的配置文件也没发现问题啊
是按住 CapsLock 然后依次按 J, K, Space 吗?

**Comment by SgAriFool** [comment]
按住CapsLock, 按JK, 松开CapsLock和JK, 再次按住CapsLock和Space

**Comment by xianyukang** [comment]
好的，复现了，我研究一下

**Comment by xianyukang** [comment]
试试用这个文件覆盖 `bin\lib` 中的同名文件，然后重启 MyKeyamp:
[KeymapManager.zip](https://github.com/user-attachments/files/17129423/KeymapManager.zip)

**Comment by SgAriFool** [comment]
覆盖之后, 没有问题了, 麻烦大佬了
