### ISSUE TITLE
MyKeymap 设置的快捷键在 Command 中不生效

### ISSUE THREAD

**Issue by toure00** [xianyukang/MyKeymap#188]
比如我创建了 RCtrl 层, 设置了 <kbd>RCtrl-h</kbd>  为 <kbd>Backspace</kbd>, 还设置了 <kbd>RCtrl</kbd> 的 SinglePress 为 <kbd>Esc</kbd> ,  但是在 Command 的 inputbox 中都没有生效

**Comment by xianyukang** [comment]
由于实现起来太复杂，所以 Command 不支持所有热键
