### ISSUE TITLE
设置界面添加设置快捷键的一个操作小逻辑问题

### ISSUE THREAD

**Issue by alexcchen** [xianyukang/MyKeymap#189]
在设置界面，点击设置-新增一个，然后点击名称，输入名称，点击网页屏幕空白处，新添加的一整条连同已经输入好的名称都不见了，目前的操作方法是先添加触发键，必须把触发键写齐全后，再点击名称，才能正常输入留存，期间，这个操作逻辑可以改为不点击该条的删除键，打死都不消失当前的设置新添加条。

**Comment by xianyukang** [comment]
有啥问题? 只填名字，然后会发生什么?
![image](https://github.com/user-attachments/assets/c1f97aba-e909-4e5f-b348-729ea948ac35)

**Comment by alexcchen** [comment]
![image](https://github.com/user-attachments/assets/60e0e59d-0e74-409e-a5a2-113f8d3634cd)
点击鼠标右侧空白处，整条填写到一半的设置就会自动删除了

**Comment by xianyukang** [comment]
`触发键` 那一列最多只允许一个配成空，试试把 Excel 的触发键补上?

**Comment by alexcchen** [comment]
但是点触发键的输入框位置，无法激活触发键输入框（按tab键也无法跳转到触发键的输入框），然后整条添加得连同名称就自动删除了，得重新添加，必须先输入触发键，再点击名称激活名称输入框输入名称，这样就就没问题，所以是个输入操作逻辑上得小问题，就是新人首次操作或者过久了来操作（新添加快捷方式的操作频率低）又得摸索下，弄明白了这样吧也能用

**Comment by xianyukang** [comment]
这个问题是因为 "会自动删除触发键重复的模式"，
你截图中的配置，已经有一个模式的触发键为空，所以新增一个会被自动删掉 ( 触发键重复了，都是空 )

**Comment by xianyukang** [comment]
嗯，总之刚刚优化了这个逻辑
