### ISSUE TITLE
持续按压一个按键

### ISSUE THREAD

**Issue by alexcchen** [xianyukang/MyKeymap#190]
CAD软件经常需要长按鼠标滚轮中键按下达到拖拽效果，结果中键就按得时灵时不灵的，可以用鼠标配套的驱动软件改写XButton1为鼠标中键功能，（长期按中键中/食指痛，用大拇指按XButton1就可以缓解中指的劳累），
但想要尝试使用mykeymap的设置来重映射XButton1为MButton这种更为通用的方法，于是设置xbutton1的singlepress为sendkeys的内容{blind}{MButton}{down}，确实可以单击xbutton1激活鼠标中键MButton的按下（可是需要松开XButton1后才会响应，按下时不响应），再次单击达到松开MButton效果，但我想要的效果是和正常的鼠标中键一样的用法，按下时候立即达到按下状态，松开后就变成鼠标中键松开的状态，
又尝试了使用自定义热键功能，可以做到XButton1一按下就sendkeys重映射启动MButton，不用等待松开XButton1，但松开XButton1自动立即释放MButton还无法做到，必须再单击左键或者单击一次XButton1可以释放MButton的按下状态，不知道有什么方法可以检测实时检测到鼠标松开了XButton1，此时再sendkyes重映射为MButton，就可以达到松开即释放MButton的效果

**Comment by alexcchen** [comment]
再结合设置的XButton1的singlepress，设置为{Esc}，失败。。。
又想到个办法，再新建一个自定义热键功能为XButton1 up，sendkeys重映射为{Mbutton}{up}，可以达到按下即响应为MButton，松开即松开MButton的初步能力，但是有时候会时序错乱，于是给XButton1的sendkeys加入延时防抖改为{MButton}{down}
sleep 200，XButton1 up的sendkeys改为{MButton}{up} sleep 200，现在效果非常好，还没什么错误产生，和原生驱动设置的效果一摸一样，开心
记录下来希望能对需要替换鼠标按键功能的开发和有这需求设置的人有所启发

**Comment by alexcchen** [comment]
学艺不精，描述有误，XButton1设置为sendkeys内容为{MButton down}，XButton1 up设置为sendkeys内容为{MButton up}就可以了，并不是延时的问题，down up 分开写就是表示上下箭头按键了，应该能连在同一个大括号一起写，不然有些场景映射后的鼠标中键功能会失效。

**Comment by xianyukang** [comment]
可以在自定义热键里重映射按键，
另外 XButton1 重映射为 MButton 后，无法再把 XButton1 用作模式的触发键
![image](https://github.com/user-attachments/assets/f116c2f6-4e51-4a94-af2f-4a799ab8a06e)

**Comment by alexcchen** [comment]
可以的，更加简洁了，厉害，MButton这个名字目前不在重映射按键的候选名称里面，我一直以为重映射按键功能只能够选择有的按键名称才行，所以用的sendkeys功能绕了一圈，建议把autohotkye的重映射按键功能候选项的所有按键名组列齐全
