### ISSUE TITLE
我写了一些链式调用函数和传多个参数的包装器，双击模型函数等等，请大佬帮忙指正。

### ISSUE THREAD

**Issue by wuqy1234** [xianyukang/MyKeymap#192]
麻烦大佬先看例子:chainCall(Send, "{text}(){}")(Send, "{left 3}")(___(inputHook_custom, "enter", 5, () => chainCall(Send, "{end}")(Send, "{left}")(Send, "{enter}")))
;包装器链条函数。柯里化思路。
chainCall(funcName, param?) {
    if IsSet(param)
        funcName(param)
    else
        funcName()
    return chainCall
}

;包装器函数，不会立即调用。三条下划线。其目的是为了解决传递多个参数的问题。
;嵌套使用此包装函数，特别方便。一个函数中要动态调用另外一个函数时，把调用的函数当参数传递，同时又不立即执行。
;例如：___(inputHook_custom, "enter", 2, ___(MsgBox, "你好"))
___(func, param*) {
    innerFunc() {
        if (IsSet(param)) {
            func(param*)
        } else {
            func()
        }
    }
    return innerFunc
}
;例如可以设置，单击为普通等号,双击发送:= ahk中的赋值等号。inputPressesValue手动输入进度值，用来模拟多击。
doubleClickModel(onceClick := "", secondClick := "", thirdClick := "", isFunction := false, functionName := "", moreFunc := false, param1 := "", param2 := "", param3 := "", inputPressesValue := 0) {
    static pressesValue := 0
    if pressesValue > 0 {
        pressesValue += 1
        return
    }
    if inputPressesValue > 0
        pressesValue := inputPressesValue
    else
        pressesValue := 1

    SetTimer After400, -400
    After400() {
        if pressesValue == 1 {
            if isFunction {
                if !moreFunc
                    functionName(onceClick)
                else {
                    if param1 != ""
                        onceClick(param1)
                    else
                        onceClick()
                }
            } else
                Send(onceClick)
        } else if pressesValue == 2 {
            if isFunction {
                if !moreFunc
                    functionName(secondClick)
                else
                {
                    if param2 != ""
                        secondClick(param2)
                    else
                        secondClick()
                }
            } else
                Send(secondClick)
        } else if pressesValue == 3 {
            if isFunction {
                if !moreFunc
                    functionName(thirdClick)
                else {
                    if param3 != ""
                        thirdClick(param3)
                    else
                        thirdClick()
                }
            } else
                Send(thirdClick)
        }
        pressesValue := 0
    }
}

**Comment by wuqy1234** [comment]
;这个钩子能够在一个按键按下后，等待另外一个按键按下，然后执行一些函数。
inputHook_custom(WaitKey := "enter", delay := 1, func := "") {
    ih := InputHook("VT" delay)
    ih.KeyOpt("{" WaitKey "}", "N+S")
    ih.OnKeyDown := KeyDown
    ih.Start()
    KeyDown(ih, vk, sc) {
        ih.Stop()
        if func != ""
            func()
    }
}

**Comment by xianyukang** [comment]
柯里化思路是如何体现的?

**Comment by xianyukang** [comment]
为啥要封装 `chainCall` 呢? 拿你举的例子来说:
```ahk
; 把这一长串
chainCall(Send, "{text}(){}")(Send, "{left 3}")(___(inputHook_custom, "enter", 5, () => chainCall(Send, "{end}")(Send, "{left}")(Send, "{enter}")))

; 改成这个
Send, "{text}(){}"
Send, "{left 3}"
fn() {
  Send, "{end}"
  Send, "{left}"
  Send, "{enter}"
}
inputHook_custom, "enter", 5, fn
```
可读性不是更好吗?

**Comment by xianyukang** [comment]
区分单击、双击、长按是容易想到的需求，自己动手写之前，可以先找找网上的例子:
- https://www.autohotkey.com/boards/viewtopic.php?t=118392
- https://www.autohotkey.com/boards/viewtopic.php?t=87211

**Comment by wuqy1234** [comment]
km.Map("*h", _ => chainCall(Send, "{text}(){}")(Send, "{left 3}")(dotAndCommas,"")(___(inputHook_custom, "enter", 5, () => chainCall(Send, "{end}")(Send, "{left}")(Send, "{enter}"))))

**Comment by wuqy1234** [comment]
这种玩法使得可塑性变强了。

**Comment by xianyukang** [comment]
> 这种玩法使得可塑性变强了。

可塑性能举个例子吗?

**Comment by wuqy1234** [comment]
km.Map("*h", _ => chainCall(Send, "{text}(){}")(Send, "{left 3}")(dotAndCommas, "")(___(inputHook_custom, "enter", 5, () => chainCall(Send, "{end} {left} {enter}"))))
这样写简短一点。

**Comment by wuqy1234** [comment]
在给触发键添加逻辑的时候，就不用重写一个自定义函数了，直接把需要的函数拼接一下就行了。上面就是一个H键的例子，在敲击了H键，会输出（）{｝，光标停留在小括号里，在5秒内敲击enter键，会把大括号切开且换行。还添加了，如果是中文输入法，那么就自动切换为英文输入法。

**Comment by wuqy1234** [comment]
dotAndCommas函数，通常是，当按下英文逗号或英文句号，那么就会切换为英文输入法。当然是通过发送shift键实现的，中英文输入法状态是通过一个变量存储的，无法读取系统里的中英文输入法状态，所以就记录一下输入法的状态。

**Comment by xianyukang** [comment]
**确实如此，有时候把简单函数写在一行里挺方便的，不用重写一个自定义函数，**
可是你给的例子不太「简短」，如果再来个 `inputHook_custom`，
会有很多嵌套括号、下划线和箭头函数，恐怕就难以阅读/维护了，

**但是自己的代码怎么写都行，按照自己的口味，怎么方便怎么来🐶**
```autohotkey
km.Map("*h", _ => chainCall(Send, "{text}(){}")(Send, "{left 3}")(dotAndCommas, "")(___(inputHook_custom, "enter", 5, () => chainCall(Send, "{end} {left} {enter}"))))
```
