### ISSUE TITLE
开个功能脑洞，阿康看着玩

### ISSUE THREAD

**Issue by Faith-Mian** [xianyukang/MyKeymap#193]
安装最新版体验了下，长按capslock+m相当于连点鼠标右键，但是右键连点好像不是很常用。

所以把这个长按操作改为右键按下数秒内不弹起，当作键盘使用“鼠标手势”的起手，接一套丝滑的小连招，如u或者capslock+u（滚轮上滑）和【鼠标右键】功能模块里的Ctrl+Shift+Tab联动。

**Comment by Faith-Mian** [comment]
别的capslock命令里也可以加一些快捷功能比如设备管理器如下，其他同理高级设置sysdm.cpl 网络连接ncpa.cpl 系统服务services.msc
```
#r
sleep 666
devmgmt.msc {enter}
```

**Comment by xianyukang** [comment]
也可以这样:
![image](https://github.com/user-attachments/assets/2eb7b38d-e3e5-4e44-a7ed-80065c710a66)

**Comment by xianyukang** [comment]
> 安装最新版体验了下，长按capslock+m相当于连点鼠标右键，但是右键连点好像不是很常用。
> 
> 所以把这个长按操作改为右键按下数秒内不弹起，当作键盘使用“鼠标手势”的起手，接一套丝滑的小连招，如u或者capslock+u（滚轮上滑）和【鼠标右键】功能模块里的Ctrl+Shift+Tab联动。

还是简单点比较容易掌握
