### ISSUE TITLE
请问QQ群怎么加入?🙏

### ISSUE THREAD

**Issue by trevim99** [xianyukang/MyKeymap#194]
请问QQ群怎么加入?🙏
可是我不知道验证讯息 😅
谢谢
🙏

![image](https://github.com/user-attachments/assets/e691e974-f25c-4525-838c-3de4570f33a6)

**Comment by xianyukang** [comment]
有个「 该账号存在风险，请谨慎操作 」，是你吗? 昵称傲松

**Comment by trevim99** [comment]
> 有个「 该账号存在风险，请谨慎操作 」，是你吗? 昵称傲松

不是我,我的暱稱是 yooung

我現在加

![image](https://github.com/user-attachments/assets/1f037171-e498-44a3-bfa4-3262d6fd3b9c)
