### ISSUE TITLE
使用自定义热键设置启动gvim时，gvim窗口总是未激活

### ISSUE THREAD

**Issue by Nashmatphysics** [xianyukang/MyKeymap#195]
阿康你好， 我在使用ahk2.0 版本的mykeymap时， 设置自定义热键#v 来启动gvim， 但是每次打开的gvim窗口都是没有激活的窗口， 导致必须手动切换程序到gvim（使其变为当前活动窗口）才能进行字符输入。 
此问题在ahk v1 版本的mykeymap中没有出现。且问题似乎主要只在gvim中发生， 其他程序正常。
另外， 启动gvim时， 似乎所有窗口都失去焦点， 没有任何窗口能接收到输入， 除非使用窗口切换操作来指定一个活动窗口。

操作系统： Windows 10 21h2
gvim版本： 9.1
mykeymap版本：2.0 beta-31

**Comment by xianyukang** [comment]
(1) 下载[这个文件](https://github.com/xianyukang/MyKeymap/blob/main/bin/RunActivate.ahk)，并移动到 data 文件夹
(2) 按下图进行配置
![image](https://github.com/user-attachments/assets/875dc448-907b-4906-a0c7-58d26e3d3c25)

**Comment by Nashmatphysics** [comment]
我试了一下, 仍然不起作用, 如下图:
![gvim](https://github.com/user-attachments/assets/4df299f4-047a-4ac2-a421-81d02eaf2d62)

并且我认为合理的操作逻辑是每次按下热键, 都启动一个新的gvim程序, 而不是激活已经打开的gvim窗口.

对于这个问题, 以下是我的猜想: 
mykeymap是否通过命令行终端去启动程序? 比如下面这个函数:
```ahk
/**
 * 通过命令行去启动程序，防止会导致以管理员启动软件的问题
 * @param target 程序路径 
 * @param arguments 参数
 * @param directory 工作目录
 * @param operation 选项 (runas/open/edit/print
 * @param show 是否显示
 */
ShellRun(target, arguments?, directory?, operation?, show?) {
  static VT_UI4 := 0x13, SWC_DESKTOP := ComValue(VT_UI4, 0x8)
  ComObject("Shell.Application").Windows.Item(SWC_DESKTOP).Document.Application
    .ShellExecute(target, arguments?, directory?, operation?, show?)
}
```
如果是的话, 那么在启动gvim的时候可能先激活的窗口是cmd命令行窗口, 而不是gvim. 因此, 在启动程序后, cmd命令行窗口关闭, 自然也就没有激活的窗口了.
总之, 可能捕捉到的是用来启动gvim的程序窗口, 从而导致gvim没法设置为活动.

我不是太了解mykeymap设置热键后, 是通过哪个函数执行启动程序的过程. 如果上面的分析是正确的话, 有没有办法可以略过启动gvim的那个程序, 来激活gvim窗口, 且不是通过固定的 "ahk_exe gvim.exe" 窗口标识符来识别每次按下热键后启动的gvim(比如通过记录启动gvim时的进程id)?

**Comment by xianyukang** [comment]
> 我认为合理的操作逻辑是每次按下热键, 都启动一个新的gvim程序, 而不是激活已经打开的gvim窗口.

把配置里的第一个参数「 要激活的窗口 」留空，就不会激活，每次都启动新的 gvim.exe

**Comment by xianyukang** [comment]
RunActivate.ahk 的作用是，启动 gvim.exe 并记录 pid，
等待 200ms，检查指定进程是否激活，如果发现没激活就激活一下，

我自测挺稳的啊，就算 gvim.exe 启动时失去焦点，也会被修正

**Comment by Nashmatphysics** [comment]
嗯嗯, 我增加了等待的时间, 然后就可以了, 可能是等待的时间过短, 导致没有检测到窗口. 
所以我把 `Sleep 200` 改成了`WinWait("ahk_pid " pid)` , 排除了程序启动快慢的因素, 然后问题完美解决. 
感谢!
