### ISSUE TITLE
最新版好像不支持caps+~吗

### ISSUE THREAD

**Issue by Faith-Mian** [xianyukang/MyKeymap#196]
这个制表键离caps键比较近，3模式使用起来也不错，就是和caps+f或caps+space配合不了，阿康考虑一下看看

**Comment by xianyukang** [comment]
怎么不回复了？不回复我就关掉 issue 咯

**Comment by Faith-Mian** [comment]
> 怎么不回复了？不回复我就关掉 issue 咯

原来如此，caps+`可用，caps+~没反应。对了，不把图中的布局设为默认是有啥考量吗？`

**Comment by xianyukang** [comment]
> > 怎么不回复了？不回复我就关掉 issue 咯
> 
> 原来如此，caps+\`可用，caps+~没反应。对了，不把图中的布局设为默认是有啥考量吗？`

你不能直接打出来 ~ 键，得按 shift
默认布局够用了，然后少一点更美观
