### ISSUE TITLE
caps+x关闭程序报错

### ISSUE THREAD

**Issue by Faith-Mian** [xianyukang/MyKeymap#199]
补充说明：此时caps在按下未弹起状态

> Error: (5) 拒绝访问。
	---- C:\``\MyKeymap2\bin\lib\Functions.ahk
	091: {
	092: {
▶	092: Return  (WinGetProcessName(winTitle) == 'ApplicationFrameHost.exe')
	092: }
	092: fn := (winTitle) => (WinGetProcessName(winTitle) == 'ApplicationFrameHost.exe')
Call stack:
C:\``\MyKeymap2\bin\lib\Functions.ahk (92) : [WinGetProcessName] Return  (WinGetProcessName(winTitle) == 'ApplicationFrameHost.exe')
C:\``\MyKeymap2\bin\lib\Functions.ahk (92) : [] Return  (WinGetProcessName(winTitle) == 'ApplicationFrameHost.exe')
C:\``\MyKeymap2\bin\lib\Functions.ahk (95) : [GetActiveProcess] If fn(winTitle)
C:\``\MyKeymap2\bin\lib\Functions.ahk (88) : [GetProcessName] Return GetActiveProcess("name")
C:\``\MyKeymap2\bin\lib\Actions.ahk (159) : [SmartCloseWindow] name := GetProcessName()
C:\``\MyKeymap2\bin\MyKeymap.ahk (76) : [] Return  SmartCloseWindow()
C:\``\MyKeymap2\bin\lib\KeymapManager.ahk (234) : [wrapper] handler(thisHotkey)
> *x
C:\``\MyKeymap2\bin\lib\KeymapManager.ahk (260) : [KeyWait] KeyWait(this.WaitKey)
C:\``\MyKeymap2\bin\lib\KeymapManager.ahk (260) : [Keymap.Prototype.Wait] KeyWait(this.WaitKey)
C:\``\MyKeymap2\bin\lib\KeymapManager.ahk (64) : [KeymapManager.Activate] keymap.Wait(startTick)
C:\``\MyKeymap2\bin\lib\KeymapManager.ahk (22) : [handler] this.Activate(subKeymap)
C:\``\MyKeymap2\bin\lib\KeymapManager.ahk (234) : [wrapper] handler(thisHotkey)
> *CapsLock

**Comment by xianyukang** [comment]
关闭什么应用时遇到这个「 拒绝访问 」错误?

**Comment by Faith-Mian** [comment]
> 关闭什么应用时遇到这个「 拒绝访问 」错误?

报告，我还真搞不清，当时内存满了导致系统许多程序未响应，我才乱按关程序的。。。

**Comment by xianyukang** [comment]
这个报错不影响使用，然后一般也不会出现，所以忽略就好
