### ISSUE TITLE
当对着某个窗口使用时，若窗口卡死则本程序也会卡死

### ISSUE THREAD

**Issue by MasouShizuka** [xianyukang/MyKeymap#20]
若使用`MyKeymap`在某个应用程序的窗口上操作，比如移动鼠标或者使用`Capslock`的功能等。

若该应用程序无响应（卡死），则本程序也会跟着卡死，比如移动鼠标过程中，卡死后鼠标会一直移动，直到强行`kill`掉`MyKeymap`。

**Comment by xianyukang** [comment]
没错是这样的,  我也经历过若干次,  除了重启程序没有很好的解决办法
