### ISSUE TITLE
这段代码能录制用户的操作，包括鼠标操作和键盘的操作。

### ISSUE THREAD

**Issue by wuqy1234** [xianyukang/MyKeymap#200]
global transcribeChainFn := "chainCall"

        timekeeper := A_TickCount, step := 0

        Hotkey("lbutton", LBT_Click, "On")
        Hotkey("lbutton Up", LBT_Click_up, "On")
        LBT_Click(*) {
            global LBT_X, LBT_Y, LBT_timekeeper
            if step = 0
                timekeeper := A_TickCount
            step++
            Send("{LButton Down}")
            MouseGetPos &LBT_X, &LBT_Y
            LBT_timekeeper := A_TickCount
        }
        LBT_Click_up(*) {
            global LBT_X, LBT_Y, LBT_timekeeper
            Send("{LButton Up}")
            MouseGetPos &LBT_up_X, &LBT_up_Y
            if A_TickCount - LBT_timekeeper < 100 {
                transcribeChainFn .= "(()=>sleep(" A_TickCount - timekeeper "))" "(()=>Click(" LBT_X "," LBT_Y ",1))"
            } else {
                transcribeChainFn .= "(()=>sleep(" LBT_timekeeper - timekeeper "))" "(()=>MouseClickDrag(`"Left`"," LBT_X "," LBT_Y "," LBT_up_X "," LBT_up_Y ",100))"
            }
            timekeeper := A_TickCount
        }
        Hotkey("Rbutton", RBT_Click, "On")
        Hotkey("Rbutton Up", RBT_Click_up, "On")
        RBT_Click(*) {
            global RBT_X, RBT_Y, RBT_timekeeper
            if step = 0
                timekeeper := A_TickCount
            step++
            Send("{RButton Down}")
            MouseGetPos &RBT_X, &RBT_Y
            RBT_timekeeper := A_TickCount
        }
        RBT_Click_up(*) {
            global RBT_X, RBT_Y, RBT_timekeeper
            Send("{RButton Up}")
            MouseGetPos &RBT_up_X, &RBT_up_Y
            if A_TickCount - RBT_timekeeper < 100 {
                transcribeChainFn .= "(()=>sleep(" A_TickCount - timekeeper "))" "(()=>MouseClick(`"Right`"," RBT_X "," RBT_Y ",1))"
            } else {
                transcribeChainFn .= "(()=>sleep(" RBT_timekeeper - timekeeper "))" "(()=>MouseClickDrag(`"Right`"," RBT_X "," RBT_Y "," RBT_up_X "," RBT_up_Y ",100))"
            }
            ; A_Clipboard := transcribeChainFn
            timekeeper := A_TickCount
        }
        Hotkey("WheelUp", WheelUp_roll, "On")
        ;通过时间计算，来判断连续滚动。如果滚动的时间间隔较大，那么就另外记录滚动的次数，同时记录时间间隔。
        WheelUp_roll(*) {
            Send("{WheelUp}")
            static wheelUpCount := 0
            if step = 0
                timekeeper := A_TickCount
            step++
            wheelUpCount++
            if wheelUpCount = 1 {
                SetTimer(gatherRollCountFn, -1000)
                gatherRollCountFn() {
                    transcribeChainFn .= "(()=>sleep(" A_TickCount - timekeeper "))" '(()=>send("{wheelUp ' wheelUpCount '}"))'
                    wheelUpCount := 0, timekeeper := A_TickCount
                }
            }
        }
        Hotkey("WheelDown", WheelDown_roll, "On")
        WheelDown_roll(*) {
            Send("{WheelDown}")
            static wheelDownCount := 0
            if step = 0
                timekeeper := A_TickCount
            step++
            wheelDownCount++
            if wheelDownCount = 1 {
                SetTimer(gatherRollCountFn, -1000)
                gatherRollCountFn() {
                    transcribeChainFn .= "(()=>sleep(" A_TickCount - timekeeper "))" '(()=>send("{wheelDown ' wheelDownCount '}"))'
                    wheelDownCount := 0, timekeeper := A_TickCount
                }
            }
        }

        SetTimer(setSendMode_InputHook, -1000) ;延时执行避免锁子模式模式。
        setSendMode_InputHook() {
            global setSendMode_ih, transcribeChainFn := "chainCall",
                timekeeper := A_TickCount, stopLoop, accumulator := ""
            static pressKey := "", pressCount := 0,
                altKey := "", ctrlKey := "", shiftKey := "", LWinKey := "",
                altKeyCount := 0, ctrlKeyCount := 0, shiftKeyCount := 0, LWinKeyCount := 0
            time := -1500
            if step = 0
                timekeeper := A_TickCount
            step++
            ; Suspend ;如果不暂停，使用了热键的按键无法记录，比如j键。
            setSendMode_ih := InputHook("V L1000")
            setSendMode_ih.KeyOpt("{All}", "N-S") ;-s为不拦截按键操作，和+V是一样的。
            setSendMode_ih.KeyOpt("{LCtrl}{RCtrl}{LAlt}{RAlt}{LShift}{RShift}{LWin}{RWin}", "-N -S")
            setSendMode_ih.OnKeyDown := KeyDown
            setSendMode_ih.OnKeyUp := KeyUp
            setSendMode_ih.Start()

            KeyDown(ih, vk, sc) {
                pressCount := 0
                pressKey := ""
            }
            KeyUp(ih, vk, sc) { ;文字输入，等等取反操作，能输入更多的内容。
                pressCount++
                pressKey := GetKeyName(Format("vk{:x}sc{:x}", VK, SC))
                if StrLen(pressKey) > 1
                    pressKey := "{" pressKey "}"
                if pressCount == 1 {
                    accumulator .= pressKey
                    SetTimer(operationRecorder, 0)
                    SetTimer(operationRecorder, time)
                    timekeeper := A_TickCount
                }
            }

            loop {
                if GetKeyState("alt", "P") {
                    altKey := "!"
                    altKeyCount++
                    if altKeyCount == 1 {
                        accumulator .= altKey
                        SetTimer(operationRecorder, 0)
                        SetTimer(operationRecorder, time)
                        timekeeper := A_TickCount
                    }
                } else
                    altKey := "", altKeyCount := 0

                if GetKeyState("ctrl", "P") {
                    ctrlKey := "^"
                    ctrlKeyCount++
                    if ctrlKeyCount == 1 {
                        accumulator .= ctrlKey
                        SetTimer(operationRecorder, 0)
                        SetTimer(operationRecorder, time)
                        timekeeper := A_TickCount
                    }
                } else
                    ctrlKey := "", ctrlKeyCount := 0

                if GetKeyState("shift", "P") {
                    shiftKey := "+"
                    shiftKeyCount++
                    if shiftKeyCount == 1 {
                        accumulator .= shiftKey
                        SetTimer(operationRecorder, 0)
                        SetTimer(operationRecorder, time)
                        timekeeper := A_TickCount
                    }
                } else
                    shiftKey := "", shiftKeyCount := 0

                if GetKeyState("LWin", "P") {
                    LWinKey := "#"
                    LWinKeyCount++
                    if LWinKeyCount == 1 {
                        accumulator .= LWinKey
                        SetTimer(operationRecorder, 0)
                        SetTimer(operationRecorder, time)
                        timekeeper := A_TickCount
                    }
                } else
                    LWinKey := "", LWinKeyCount := 0

                if IsSet(stopLoop)
                    break
            }

            operationRecorder() {
                transcribeChainFn .= "(()=>sleep(" A_TickCount - timekeeper "))" '(()=>send("' accumulator '"))'
                accumulator := ""
            }

        }
如果需要的话可以下载我的包:https://gitee.com/wuqingyongwu/my-keymap

**Comment by wuqy1234** [comment]
其中可能会有bug，还请大佬指正。

**Comment by xianyukang** [comment]
> 其中可能会有bug，还请大佬指正。

你自己测嘛，
一般自测过就大概率没问题了

**Comment by wuqy1234** [comment]
完美运行

**Comment by xianyukang** [comment]
> 完美运行

可以 👍🏻👍🏻👍🏻

**Comment by wuqy1234** [comment]
global transcribeChainFn := "chainCall"

        timekeeper := A_TickCount, step := 0

        Hotkey("lbutton", LBT_Click, "On")
        Hotkey("lbutton Up", LBT_Click_up, "On")
        LBT_Click(*) {
            global LBT_X, LBT_Y, LBT_timekeeper
            if step = 0
                timekeeper := A_TickCount
            step++
            Send("{LButton Down}")
            MouseGetPos &LBT_X, &LBT_Y
            LBT_timekeeper := A_TickCount
        }
        LBT_Click_up(*) {
            global LBT_X, LBT_Y, LBT_timekeeper
            Send("{LButton Up}")
            MouseGetPos &LBT_up_X, &LBT_up_Y
            if A_TickCount - LBT_timekeeper < 100 {
                transcribeChainFn .= "(()=>sleep(" A_TickCount - timekeeper "))" "(()=>Click(" LBT_X "," LBT_Y ",1))"
            } else {
                transcribeChainFn .= "(()=>sleep(" LBT_timekeeper - timekeeper "))" "(()=>MouseClickDrag(`"Left`"," LBT_X "," LBT_Y "," LBT_up_X "," LBT_up_Y ",100))"
            }
            timekeeper := A_TickCount
        }
        Hotkey("Rbutton", RBT_Click, "On")
        Hotkey("Rbutton Up", RBT_Click_up, "On")
        RBT_Click(*) {
            global RBT_X, RBT_Y, RBT_timekeeper
            if step = 0
                timekeeper := A_TickCount
            step++
            Send("{RButton Down}")
            MouseGetPos &RBT_X, &RBT_Y
            RBT_timekeeper := A_TickCount
        }
        RBT_Click_up(*) {
            global RBT_X, RBT_Y, RBT_timekeeper
            Send("{RButton Up}")
            MouseGetPos &RBT_up_X, &RBT_up_Y
            if A_TickCount - RBT_timekeeper < 100 {
                transcribeChainFn .= "(()=>sleep(" A_TickCount - timekeeper "))" "(()=>MouseClick(`"Right`"," RBT_X "," RBT_Y ",1))"
            } else {
                transcribeChainFn .= "(()=>sleep(" RBT_timekeeper - timekeeper "))" "(()=>MouseClickDrag(`"Right`"," RBT_X "," RBT_Y "," RBT_up_X "," RBT_up_Y ",100))"
            }
            ; A_Clipboard := transcribeChainFn
            timekeeper := A_TickCount
        }
        Hotkey("WheelUp", WheelUp_roll, "On")
        ;通过时间计算，来判断连续滚动。如果滚动的时间间隔较大，那么就另外记录滚动的次数，同时记录时间间隔。
        WheelUp_roll(*) {
            Send("{WheelUp}")
            static wheelUpCount := 0
            if step = 0
                timekeeper := A_TickCount
            step++
            wheelUpCount++
            if wheelUpCount = 1 {
                SetTimer(gatherRollCountFn, -1000)
                gatherRollCountFn() {
                    transcribeChainFn .= "(()=>sleep(" A_TickCount - timekeeper "))" '(()=>send("{wheelUp ' wheelUpCount '}"))'
                    wheelUpCount := 0, timekeeper := A_TickCount
                }
            }
        }
        Hotkey("WheelDown", WheelDown_roll, "On")
        WheelDown_roll(*) {
            Send("{WheelDown}")
            static wheelDownCount := 0
            if step = 0
                timekeeper := A_TickCount
            step++
            wheelDownCount++
            if wheelDownCount = 1 {
                SetTimer(gatherRollCountFn, -1000)
                gatherRollCountFn() {
                    transcribeChainFn .= "(()=>sleep(" A_TickCount - timekeeper "))" '(()=>send("{wheelDown ' wheelDownCount '}"))'
                    wheelDownCount := 0, timekeeper := A_TickCount
                }
            }
        }

        SetTimer(setSendMode_InputHook, -1000) ;延时执行避免锁子模式模式。
        setSendMode_InputHook() {
            global setSendMode_ih, transcribeChainFn := "chainCall", hkTip,
                timekeeper := A_TickCount, stopLoop := false, accumulator := ""
            time := -1500 ;设置定时器多少毫秒后执行一次并结束的时间。
            if step = 0
                timekeeper := A_TickCount
            step++
            ; Suspend ;如果不暂停，使用了热键的按键无法记录，比如j键。
            setSendMode_ih := InputHook("V L1000")
            setSendMode_ih.KeyOpt("{All}", "N-S") ;-s为不拦截按键操作，和+V是一样的。
            setSendMode_ih.KeyOpt("{LCtrl}{RCtrl}{LAlt}{RAlt}{LShift}{RShift}{LWin}{RWin}", "-N -S")
            setSendMode_ih.OnKeyDown := KeyDown
            setSendMode_ih.OnKeyUp := KeyUp
            setSendMode_ih.Start()
            hkTip := customTip("键盘钩子已开启", false, 892, 1080)

            KeyDown(ih, vk, sc) {
                pressCount := 0
                pressKey := ""
            }
            ;是否是其他按键，非修饰键，当其他非修饰键按下后，otherKey为true，这样就方便以那种格式记录修饰键。
            otherKey := false
            KeyUp(ih, vk, sc) { ;文字输入，等等取反操作，能输入更多的内容。
                pressCount++
                pressKey := GetKeyName(Format("vk{:x}sc{:x}", VK, SC))
                if StrLen(pressKey) > 1
                    pressKey := "{" pressKey "}"
                if pressCount == 1 {
                    accumulator .= pressKey
                    SetTimer(operationRecorder, 0)
                    SetTimer(operationRecorder, -100)
                    timekeeper := A_TickCount
                    otherKey := true
                }
            }
            ;设一个定时器，按下去开启定时器，等待所有按下去的键松开立马执行一些操作，并结束定时器。

            pressKey := "", pressCount := 0
            altKey := "", ctrlKey := "", shiftKey := "", LWinKey := ""
            altKeyCount := 0, ctrlKeyCount := 0, shiftKeyCount := 0, LWinKeyCount := 0
            altKeyCount2 := 2, ctrlKeyCount2 := 2, shiftKeyCount2 := 2, LWinKeyCount2 := 2
            modifierKeyBox := []

            modifierKeyMonitor() {
                if modifierKeyBox.length = 0 { ;等待所有按下的修饰键释放，才执行下面的定时器。
                    SetTimer(operationRecorder, 0)
                    SetTimer(operationRecorder, -100)
                    SetTimer(modifierKeyMonitor, 0) ;清除修饰键的定时器
                }
            }

            operationRecorder() {
                if modifierKeyBox.length > 0 { ;只有非修饰键释放才执行，其中的副作用是，在最后的修饰键释放了，会把修饰键录入。
                    transcribeChainFn .= "(()=>sleep(" A_TickCount - timekeeper "))" '(()=>send("' altKey ctrlKey shiftKey LWinKey pressKey '"))'
                } else { ;所有的键都释放了，就执行下面的函数。就执行下面的函数。就执行下面的函数。
                    if otherKey {
                        if accumulator != "" 
                            transcribeChainFn .= "(()=>sleep(" A_TickCount - timekeeper "))" '(()=>send("' accumulator '"))'
                    } else {
                        ;为什么没有副作用，是因为在非修饰键释放的时候，把收集器中的字符清空了，
                        ;同时otherKey被改为false，进入了这个判断，所以不会重写。
                        accumulator := StrReplace(accumulator, "!", "{alt}")
                        accumulator := StrReplace(accumulator, "^", "{ctrl}")
                        accumulator := StrReplace(accumulator, "+", "{shift}")
                        accumulator := StrReplace(accumulator, "#", "{LWin}")
                        if accumulator != ""
                            transcribeChainFn .= "(()=>sleep(" A_TickCount - timekeeper "))" '(()=>send("' accumulator '"))'
                    }
                }
                otherKey := false
                accumulator := ""
            }

            loop {
                if GetKeyState("alt", "P") {
                    altKey := "!"
                    altKeyCount++, altKeyCount2 := 0
                    if altKeyCount == 1 {
                        modifierKeyBox.push("down")
                        accumulator .= altKey
                        SetTimer(modifierKeyMonitor, 0)
                        SetTimer(modifierKeyMonitor, 10)
                        timekeeper := A_TickCount
                    }
                } else {
                    altKeyCount2++
                    if altKeyCount2 == 1 {
                        modifierKeyBox.pop()
                        altKey := "", altKeyCount := 0
                    }
                }

                if GetKeyState("ctrl", "P") {
                    ctrlKey := "^"
                    ctrlKeyCount++, ctrlKeyCount2 := 0
                    if ctrlKeyCount == 1 {
                        modifierKeyBox.push("down")
                        accumulator .= ctrlKey
                        SetTimer(modifierKeyMonitor, 0)
                        SetTimer(modifierKeyMonitor, 10)
                        timekeeper := A_TickCount
                    }
                } else {
                    ctrlKeyCount2++
                    if ctrlKeyCount2 == 1 {
                        modifierKeyBox.pop()
                        ctrlKey := "", ctrlKeyCount := 0
                    }
                }

                if GetKeyState("shift", "P") {
                    shiftKey := "+"
                    shiftKeyCount++, shiftKeyCount2 := 0
                    if shiftKeyCount == 1 {
                        modifierKeyBox.push("down")
                        accumulator .= shiftKey
                        SetTimer(modifierKeyMonitor, 0)
                        SetTimer(modifierKeyMonitor, 10)
                        timekeeper := A_TickCount
                    }
                } else {
                    shiftKeyCount2++
                    if shiftKeyCount2 == 1 {
                        modifierKeyBox.pop()
                        shiftKey := "", shiftKeyCount := 0
                    }
                }

                if GetKeyState("LWin", "P") {
                    LWinKey := "#"
                    LWinKeyCount++, LWinKeyCount2 := 0
                    if LWinKeyCount == 1 {
                        modifierKeyBox.push("down")
                        accumulator .= LWinKey
                        SetTimer(modifierKeyMonitor, 0)
                        SetTimer(modifierKeyMonitor, 10)
                        timekeeper := A_TickCount
                    }
                } else {
                    LWinKeyCount2++
                    if LWinKeyCount2 == 1 {
                        modifierKeyBox.pop()
                        LWinKey := "", LWinKeyCount := 0
                    }
                }

                if stopLoop ;当按下Mbutton或Ecs时，停止循环，当再次开启钩子时应当重新开始循环。
                    break
            }

        }

**Comment by wuqy1234** [comment]
我重新修改了一些代码，现在能非常完美的录制用户的操作。
