### ISSUE TITLE
大写模式下的问题

### ISSUE THREAD

**Issue by Alddp** [xianyukang/MyKeymap#201]
开大写时光标在输入框时按ctrl会弹出命令框, 按capslock+w会出现切换大小写的弹窗

**Comment by xianyukang** [comment]
怎么复现呢? 发一下配置文件和复现步骤?

**Comment by Alddp** [comment]
[config.json](https://github.com/user-attachments/files/17691404/config.json)
我的配置是shift+cap切换大小写，切换为大写时光标点进输入框按ctrl就和按capslock效果一样，输入法是搜狗，ctrl切换大小写，小鹤双拼

**Comment by xianyukang** [comment]
> 输入法是搜狗，ctrl切换大小写
这个 ctrl 在哪配置？我翻了下搜狗的配置，没找到

**Comment by xianyukang** [comment]
这个问题是搜狗输入法的特殊逻辑：

在开启大写的前提下，
按下搜狗输入法的中英文切换键（如 Shift、Ctrl），
**搜狗输入法会帮用户按一次 CapsLock 键关掉大写**

所以先按 `Shift+CapsLock` 关掉大写，再按 `Ctrl` 切换中英文，就能避开这个问题
