### ISSUE TITLE
增加对 Caps Lock 按键的设置

### ISSUE THREAD

**Issue by min-ye-tfs-by** [xianyukang/MyKeymap#202]
1. 短按 Caps Lock 还是切换大小写；
2. 命令窗口使用其他快捷键触发；
3. 长按 Caps Lock 功能和现在一样不变。

请问可以实现这样的配置么，目前设置了 CapsLock 功能为切换大小写后，长按功能就不起效果了。

**Comment by xianyukang** [comment]
可以啊，把 CapsLock 模式的 SinglePress 键配成「 切换大小写 」就行了
![image](https://github.com/user-attachments/assets/d1609eb3-947d-4e2e-8ad1-f64e494fb8b4)
