### ISSUE TITLE
在小破站上看到code果果发的配置视频，太神奇了，还整合了鼠标手势

### ISSUE THREAD

**Issue by laoyaog** [xianyukang/MyKeymap#204]
她设置的功能好多啊，可是我下了最新的32版本没发现她那么多功能，况且她还用的30版本的。都是自己添加的功能吗？

**Comment by xianyukang** [comment]
嗯，都是他自己添加的功能，写了很多自定义脚本，感兴趣的话，可以进群找他私聊

**Comment by laoyaog** [comment]
找到了，刚进的群，谢谢阿康和各位小伙伴
