### ISSUE TITLE
不要把开始菜单里的快捷方式自动复制到shortcuts目录

### ISSUE THREAD

**Issue by iamqiz** [xianyukang/MyKeymap#205]
自动复制会导致shortcuts目录很杂乱,用户并不想在mykeymap里启动所有那些快捷方式
而且如果开始菜单里的快捷方式更新了,那mykeymap要重新复制过来吗?能跟着一起更新吗?如果重新复制过来,那发生重名怎么处理?
我建议先询问用户是否复制,用户同意再复制

**Comment by iamqiz** [comment]
可以把复制的快捷方式放到shortcuts目录下的子目录里,比如Auto 或 StartMenu
这样不会杂乱和避免重名,用户可以在shortcuts目录下或自己新建子目录放自己的快捷方式
另外建议在设置里加个开关,控制是否自动复制快捷方式

**Comment by xianyukang** [comment]
> 可以把复制的快捷方式放到shortcuts目录下的子目录里,比如Auto 或 StartMenu
> 这样不会杂乱和避免重名,用户可以在shortcuts目录下或自己新建子目录放自己的快捷方式
> 另外建议在设置里加个开关,控制是否自动复制快捷方式
> 

tools 文件夹可以随便放自己的快捷方式

**Comment by iamqiz** [comment]
你自动复制快捷方式的目的是什么? 默认的功能需要? 用户想要用shortcuts目录的快捷方式不会自己复制?

**Comment by iamqiz** [comment]
目的是搜索启动电脑里已安装程序?

**Comment by xianyukang** [comment]
> 你自动复制快捷方式的目的是什么? 默认的功能需要? 用户想要用shortcuts目录的快捷方式不会自己复制?

(1) 使用快捷方式启动 UWP 应用比较简单 (也有复杂的做法，我没研究)
(2) 生成快捷方式列表放到 `shortcuts` 里，方便在配置时自动补全 `shortcuts\app.lnk`

<s>感觉您语气可以稍微平和点</s>
