### ISSUE TITLE
建议增加一个全屏下自动禁用的选项

### ISSUE THREAD

**Issue by xkonglong** [xianyukang/MyKeymap#21]
rt

**Comment by Faith-Mian** [comment]
哈哈 和小恐龙排版助手冲突吗

**Comment by meetyoucrash** [comment]
希望可以加个进程或者窗口的排除列表
根据是否运行指定进程，或者打开指定窗口来暂停软件的规则。

**Comment by alexcchen** [comment]
设置快捷键
alt+‘
作为暂停/恢复键就挺好用的，可以应个急，也挺便捷

**Comment by xianyukang** [comment]
> 希望可以加个进程或者窗口的排除列表 根据是否运行指定进程，或者打开指定窗口来暂停软件的规则。

可以添加排除列表了:
1. 打开设置
2. 点击「 编辑程序分组 」
3. 修改其中的「 Exclude 」分组

**Comment by xianyukang** [comment]
判定全屏有点麻烦啊，
现在有排除列表了，再加上手动的暂停/恢复热键，能应付大部分情况
