### ISSUE TITLE
提供j模式的按下时间判断调整参数

### ISSUE THREAD

**Issue by rywiki** [xianyukang/MyKeymap#22]
我平时是用全拼打字，所以击键速度可能稍微快了一点，导致开着mykeymap的时候，敲j到时候总是被认为是按下状态。没法在开着的时候正常录入汉字。而我又不想一直做暂停切换，这样，mykeymap本身都价值就会大打折扣。我在想，会不会可以调整一下j的按下段时间判断能够解决这个问题，但是在设置界面中没有相应的设置。
我还去看了ahk介绍，发现，keywait并没有相关的参数。

**Comment by xianyukang** [comment]
如果按下 J 就立刻发送 J 键,  会导致 J + EDSF 模拟上下左右时多打一个 J 键
所以现在的逻辑是等 J 弹起时才发送 J 键

你说的「 调整按键时间 」
更具体一点的思路是什么 ?

**Comment by rywiki** [comment]
> 

没什么太好的思路。也许我的逻辑当时没转过来。现在我面临的问题就是，打字的时候j和后面的按键间隔时间太短了，以至于mykeymap认为我的j还是按下的状态。实际上j已经抬起来了。可j还是没法正常输入进去。不太清楚这个抬起的判断是否有延后才导致这种问题。
你们输入的文字的时候没有遇到这种情况么？我在想是不是全拼的击键速度需要比双拼快原因，哈哈。

**Comment by xianyukang** [comment]
在 J 弹起的瞬间会退出 J 模式并发送 J 键
你可能打字太快然后被判定成了 J + 某个键,  试试等 J 输出了再按下一个键吧
或者也可以试试「 逗号模式 」,  侵入性低、功能够用、作为前置键也挺好按的

我打算下个版本把 「 逗号模式 」完善一下,  默认开启
这样对普通用户来说,  适应成本低很多

**Comment by qstdnx** [comment]
> 

我打字速度不快，但是也遇到同样的问题，我最后把j键的功能全都迁移到了caps+space上了，纠结是不是改成纯space来触发。

**Comment by qstdnx** [comment]
> 在 J 弹起的瞬间会退出 J 模式并发送 J 键 你可能打字太快然后被判定成了 J + 某个键, 试试等 J 输出了再按下一个键吧 或者也可以试试「 逗号模式 」, 侵入性低、功能够用、作为前置键也挺好按的
> 
> 我打算下个版本把 「 逗号模式 」完善一下, 默认开启 这样对普通用户来说, 适应成本低很多

我打字速度不快，但是也遇到同样的问题，我最后把j键的功能全都迁移到了caps+space上了，纠结是不是改成纯space来触发。

**Comment by xianyukang** [comment]
句号 、空格 、逗号 、....都可以作为前置键,  
这里面我推荐「 句号键 」,  它的侵入性低、也比较好按
另外 MyKeymap 1.1.8 把文字编辑中所有常用键都列出来了, 方便自己改一套合适的键位

空格键和 J 键都很好按, 可惜各有各的问题 (<s>如果常规键盘上有两个空格键就好了 😂</s>)

**Comment by XDwanj** [comment]
我觉得用space作为前置键很不错, 我现在就是, 毕竟很少有按住不动一直长空格的机会, 都是一次打两个或者一个, 舍弃也没什么大问题
😃

**Comment by fllffl** [comment]
不同的打字习惯对于j键的感受可能会有所不同。我打字习惯连键，例如打“jiu”，我会按下j，然后接着按下i键，然后再依次抬起j、i键，这样就比较容易误触到j键功能。我在最开始也想到能不能给j键设定一个触发时间，例如我按下j键0.5s后才进入j键功能。不过找了一圈没有找到这样的设置，此路不通。
但是我仍然想使用j键功能，所以我简单做了如下修改来改善j键功能的使用体验：
1. j键+i 改为输入"ji"字符。
2. j键+u改为输入"ju"字符。
3. j键+l改为选中整行

上述改动仅对以下情况有所帮助：
输入汉字时，并且会把拼音打全。例如“文件”，会输入“wenjian”而不是“wj”

下面提供几个比较常用的使用j键的词，可以测试一下这种方式适不适合自己：
1. 就像
2. 几个
3. 文件夹加密
4. 软件
5. 唧唧复唧唧

**Comment by xianyukang** [comment]
@fllffl 有道理,  全拼打字中 `J` 的下一个键大概率是 `I`,  把 `j + i` 改成输入 ji 能减少一些误触
