### ISSUE TITLE
切换窗口到其他屏幕会蓝屏

### ISSUE THREAD

**Issue by iuxt** [xianyukang/MyKeymap#23]
电脑是 联想 R7000 2020 款， 没有设置独显直连， 蓝屏会出现在全屏浏览器 或 vscode 按下CapsLock+D ，一般按2-3次就会蓝屏重启。
![image](https://user-images.githubusercontent.com/23610854/163504165-d9e445c6-8f47-4e23-a8a3-7a90ae2c7008.png)

**Comment by xianyukang** [comment]
Capslock + D 只不过是模拟了 Win + Shift + Right
你可以直接按 Win + Shift + Right 试试

( 系统蓝屏什么的,  咱也解决不了

**Comment by iuxt** [comment]
感谢回复，已经确认了是Nvidia显卡驱动的问题，使用快捷键切换也会蓝屏，升级Nvidia显卡驱动解决了。
