### ISSUE TITLE
鼠标移动模块能否换成capslockx那种

### ISSUE THREAD

**Issue by qstdnx** [xianyukang/MyKeymap#24]
鼠标移动模块好像只能一个方向移动，不能斜向移动，而且快移动是瞬移也导致了难以很快定位了，放开cap后虽然可以精确定位，但是经常忘记点一下左右键让它关闭。之前记得capslockx的鼠标移动做得非常完善。
https://github.com/snomiao/CapsLockX

**Comment by MarkIlV** [comment]
附议

**Comment by xianyukang** [comment]
根据你们日常使用 CapslockX 的模拟鼠标的经验,  
能否给出一些为什么 CapslockX 的鼠标移动更好用的理由?
此外我觉得 MyKeymap 的直上直下,  没有加速度,  也挺好的

**Comment by MarkIlV** [comment]
个人觉得CapsLockX唯一更好用的一点是模拟鼠标时，当同时按住上（下）＋左（右）时，鼠标的轨迹是斜向的，这样操作起来感觉更加自然一些，而MyKeymap并不是，其他的如键位和加速度，我觉得还是Mykeymap好一些

**Comment by xianyukang** [comment]
> 个人觉得CapsLockX唯一更好用的一点是模拟鼠标时，当同时按住上（下）＋左（右）时，鼠标的轨迹是斜向的，这样操作起来感觉更加自然一些，而MyKeymap并不是，其他的如键位和加速度，我觉得还是Mykeymap好一些

我尝试过往 MyKeymap 中添加同时按下「 右+上 」则往右上角移动
感觉没有提升多少速度or便利性,  反而失去了直上直下的简单易用
MyKeymap 移动鼠标的速度很快,  所以走直线并不比走斜角慢多少

**Comment by MarkIlV** [comment]
> 

好吧(╯▽╰)

**Comment by qstdnx** [comment]
> 根据你们日常使用 CapsLockX 的模拟鼠标的经验, 能否给出一些为什么 CapsLockX 的鼠标移动更好用的理由? 此外我觉得 MyKeymap 的直上直下, 没有加速度, 也挺好的

一段时间的使用，发现这个功能没什么用，基本不会用键盘控制鼠标( ˙-˙ )硬要说的话，长按加速直接移动到大概位置，然后短按微调，用习惯了应该都差不多
