### ISSUE TITLE
请问微软应用商店的应用如何添加启动

### ISSUE THREAD

**Issue by harleywong** [xianyukang/MyKeymap#25]
比如计算器之类的应用，怎么设置启动路径？

**Comment by xianyukang** [comment]
应用商店里的 UWP 应用需要借助「 快捷方式 」启动,  参考这里的例子:
![image](https://user-images.githubusercontent.com/24707226/167064348-9c9b03b3-25dc-4206-ba6c-5bbd601e3c64.png)

**Comment by harleywong** [comment]
> 应用商店里的 UWP 应用需要借助「 快捷方式 」启动, 参考这里的例子: ![image](https://user-images.githubusercontent.com/24707226/167064348-9c9b03b3-25dc-4206-ba6c-5bbd601e3c64.png)

感谢，已经成功设置！
