### ISSUE TITLE
输入SE报错,进入不去设置页面了，能看看是哪里出错了吗

### ISSUE THREAD

**Issue by 2198764529** [xianyukang/MyKeymap#28]
![image](https://user-images.githubusercontent.com/46187375/173102346-d0e97e9e-0bd7-44fc-9654-d85de97c02d8.png)

**Comment by xianyukang** [comment]
可能是杀毒软件把 bin\ahk.exe 删掉了,  
你检查一下 bin\ahk.exe 和 bin\openSettings.ahk 是否存在
如果不存在,  就暂时关掉杀毒软件,  然后重新解压 MyKeymap.7z

**Comment by 2198764529** [comment]
还真是360的锅，回头就卸掉它。
