### ISSUE TITLE
center_window_to_current_monitor 是加了限定吗？

### ISSUE THREAD

**Issue by harleywong** [xianyukang/MyKeymap#30]
center_window_to_current_monitor 这个窗口调整是加了限定吗？到一定值之后再加就不能放大了。记得以前的版本可以再放大的。

![Snipaste_2022-06-23_11-07-23](https://user-images.githubusercontent.com/34861262/175198928-4f03ec42-e057-44bc-9656-dd4a71c926b3.jpg)
![Snipaste_2022-06-23_11-05-26](https://user-images.githubusercontent.com/34861262/175198934-c8766673-cc46-48e6-b3b1-0fefd15faa62.jpg)

**Comment by xianyukang** [comment]
没错加了限制，最大宽高为屏幕的 90%

因为有的用户屏幕特别小，1200x800 的窗口就超出屏幕范围了，所以加了上述限制

下个版本会改成 100%

**Comment by xianyukang** [comment]
第二个函数没有加限制,  例如 `set_window_position_and_size(10, 10, 1200, 800)`
试试暂时用这个函数解决?

**Comment by xianyukang** [comment]
你可以按这个 commit 修改 bin\functions.ahk
https://github.com/xianyukang/MyKeymap/commit/dec8b53e81f8b63ac118f2f5c892670c9741bfe4
