### ISSUE TITLE
是否能设置“空格模式”的空格键按键触发的延迟？打字有时会导致会误操作.

### ISSUE THREAD

**Issue by mind2sear** [xianyukang/MyKeymap#31]
如题

**Comment by xianyukang** [comment]
(1) 打开 bin\templates\script.ahk 并搜索 {% if Settings.SpaceMode %}
(2) 用下面的代码替换

*Space::
    thisHotkey := A_ThisHotkey
    disableOtherHotkey(thisHotkey)
    ; 延时 0.1 秒
    keywait Space, T0.1
    if ErrorLevel {
        SpaceMode := true
        keywait Space
    }
    SpaceMode := false
    if (A_PriorKey == "Space" && A_TimeSinceThisHotkey < 350)
        send, {blind}{Space} 
    enableOtherHotkey(thisHotkey)
    return

(3) 打开 MyKeymap 设置点击保存,  以重新生成脚本,  然后重启 MyKeymap
(4) 改完后的代码如下图,  如果方便的话,  麻烦反馈下这样修改后是否能减少误触

![image](https://user-images.githubusercontent.com/24707226/180759797-4326430c-e598-4f7d-bc65-df45d9dbbf8c.png)

**Comment by mind2sear** [comment]
> (1) 打开 bin\templates\script.ahk 并搜索 {% if Settings.SpaceMode %} (2) 用下面的代码替换
> 
> *Space:: thisHotkey := A_ThisHotkey disableOtherHotkey(thisHotkey) ; 延时 0.1 秒 keywait Space, T0.1 if ErrorLevel { SpaceMode := true keywait Space } SpaceMode := false if (A_PriorKey == "Space" && A_TimeSinceThisHotkey < 350) send, {blind}{Space} enableOtherHotkey(thisHotkey) return
> 
> (3) 打开 MyKeymap 设置点击保存, 以重新生成脚本, 然后重启 MyKeymap (4) 改完后的代码如下图, 如果方便的话, 麻烦反馈下这样修改后是否能减少误触
> 
> ![image](https://user-images.githubusercontent.com/24707226/180759797-4326430c-e598-4f7d-bc65-df45d9dbbf8c.png)

测试了一下,有一定的改善,但在快速击键的时候还是会对打字造成一定的影响.

**Comment by Ravenclawer** [comment]
感觉空格模式更适合有分裂空格的机械键盘
