### ISSUE TITLE
vscode中在9模式下绑定的部分按键触发错误

### ISSUE THREAD

**Issue by shaddollxz** [xianyukang/MyKeymap#32]
如题，我在`9模式`下绑定了`E D G`三个按键，它们并没有按设置时的期待运作
通过在`vscode`的`键盘快捷方式`面板中输入绑定的按键发现它们分别被绑定为`shift + alt + f5`、`alt + f5`、`ctrl + shift + f5`
同时`X C V`三个按键不会被输入

```
MyKeymap版本：1.1.18
vscode版本：1.70.0
```

**Comment by xianyukang** [comment]
如图,  你可以在这里把 E、D、G 三个键针对 vscode 的设置清除掉.
![image](https://user-images.githubusercontent.com/24707226/184479622-973032c9-e015-4782-95c6-f9771e87c8ea.png)

**Comment by shaddollxz** [comment]
> 如图, 你可以在这里把 E、D、G 三个键针对 vscode 的设置清除掉. ![image](https://user-images.githubusercontent.com/24707226/184479622-973032c9-e015-4782-95c6-f9771e87c8ea.png)

抱歉刚才忘了附图，我这里是重新自定义的映射，它们都是设置的全局生效
![图片](https://user-images.githubusercontent.com/56341682/184479687-a332dd1d-fcfb-4b6d-acbe-69233fa461be.png)

**Comment by xianyukang** [comment]
因为针对 vscdoe 的「 分应用设置 」优先级高于「 全局生效 」
所以还是得把 E、D、G 三个键在 vscdoe 下配成`什么也不做`,  才能符合你的预期.
