### ISSUE TITLE
关于文件编码的问题

### ISSUE THREAD

**Issue by MasouShizuka** [xianyukang/MyKeymap#33]
更新了版本1.2.1后，启动`mykeymap`会以`gbk`编码读取`mykeymap.ahk`，而设置保存时会写入`utf-8`编码的`mykeymap.ahk`，导致需要手动从`utf-8`转为`gbk`，否则会出错
而之前的版本，启动`mykeymap`会以`utf-8`编码读取`mykeymap.ahk`

**Comment by xianyukang** [comment]
你是使用 git clone 下载的 MyKeymap 吗?  
如果是,  需要把 config-back/templates/script2.ahk 从 `UTF-8` 改成 `UTF-8 with BOM`

我从官网下载软件,  检查了文件编码,  都是 `UTF-8 with BOM`, 没错呀, 尝试运行也没有报错.

![image](https://user-images.githubusercontent.com/24707226/184785533-905cb195-3d46-4746-b30a-ed0a1ea5a7f3.png)

**Comment by MasouShizuka** [comment]
不是，是从 [https://static.xianyukang.com/MyKeymap-1.2.1.7z](https://static.xianyukang.com/MyKeymap-1.2.1.7z) 下载的

**Comment by MasouShizuka** [comment]
解决了，重新下载了，将`UTF-8 with BOM` 的 `script2.ahk`覆盖了就可以了
