### ISSUE TITLE
MyKeymap-1.2.3 无法新增缩写

### ISSUE THREAD

**Issue by feitian6186** [xianyukang/MyKeymap#34]
MyKeymap-1.2.3 无法新增缩写，回车后没有反应。

**Comment by xianyukang** [comment]
我试了下,  没有遇到你说的问题:


https://user-images.githubusercontent.com/24707226/187647489-23627d06-e6a5-4a9b-ac95-63d4bd5b4545.mp4

**Comment by feitian6186** [comment]
好的。公司的电脑不可以，但是家里的可以。

还是一个建议，现在的按键都是组合键，是否可以单键操作？ 之前在网上搜索到一个 ahk 程序，当时CapsLock 开启时，可以对键盘映射。例如把j 映射成下 ，k 映射成上等，类似vim 的模式的感觉。代码如下，
SetStoreCapslockMode, Off
CoordMode, ToolTip, Screen

$CapsLock::
KeyWait, CapsLock
if(A_PriorKey<>"CapsLock"){
return
}else if(A_TimeSincePriorHotkey>0 && A_TimeSincePriorHotkey<300){
CapsLockMode := 2
SetCapsLockState, On
}else{
CapsLockMode := CapsLockMode==2 ? 0 : !CapsLockMode
SetCapsLockState, Off
}
if(CapsLockMode=1){
ToolTip, CapsLock Mode, 0, 600, 2
}else{
ToolTip,,,,2
}
Return

#If, CapsLockMode=1

 u::PgUp
 d::PgDn
 j::Down
 ; ↑
 k::Up
 ; ←
 h::Left
 ; →
 l::Right
 ; Home
 a::Home
 ; ctrl+shift+home
 ^+a::^+Home
 ; ctrl+shift+←
 ^+h::^+Left
 ; ctr+shift+→
 ^+l::^+Right
 ; End
 e::End
RAlt::AppsKey
BackSpace::Delete
; 左键
 F1::LButton
 F2::RButton
; 关闭程序
#q::!F4
; 我的电脑
;F12::#e
^BackSpace::Delete   
#If



; ~LShift::
; if (A_PriorHotkey != "~LShift" or A_TimeSincePriorHotkey > 400)
; {	
; 	KeyWait,LShift
; 	return
; }
; send {Pause}
; return

------
不知道是否融入到现在的capslk键上，  或改成数字键开启或scroll lock 开启

**Comment by xianyukang** [comment]
你可以下载这个预览版,  然后把 Caps Up 配成「 锁定当前模式 」,  实现单键操作:
(1) [MyKeymap-1.2.4-preview5.7z](https://static.xianyukang.com/MyKeymap-1.2.4-preview5.7z)
(2) 如图:
![image](https://user-images.githubusercontent.com/24707226/187760664-9297e4b6-1cc9-4315-894b-beab99940506.png)
