### ISSUE TITLE
caps指令

### ISSUE THREAD

**Issue by Faith-Mian** [xianyukang/MyKeymap#38]
阿康你好，一直在用旧版1028，最近更新到了新版发现没有单独禁用capslock指令（就是capslock输入框）的按钮，但又需要其他capslock功能，有啥好办法吗？

**Comment by xianyukang** [comment]
Capslock 模式里面有个 「 Caps Up 」,  表示短按 Capslock,  可以把它配成「 切换 Capslock 状态 」

**Comment by Faith-Mian** [comment]
> Capslock 模式里面有个 「 Caps Up 」, 表示短按 Capslock, 可以把它配成「 切换 Capslock 状态 」

已解决，谢谢阿康
