### ISSUE TITLE
关于修改默认前置键的建议

### ISSUE THREAD

**Issue by R4x7651** [xianyukang/MyKeymap#39]
个人觉得默认前置键是否可以由用户自定义呢，这样Mykeymap的定制化程度可能会更高，比如我个人会更偏向于将前置键F改为左ALT

**Comment by xianyukang** [comment]
如果希望把 Capslock + F 改成 Capslock + Alt
可以试试 MyKeymap 的 Capslock + Space 模式啊
同样也是使用「 拇指 」按下第二个键,  另外空格键比左 Alt 更方便吧

**Comment by MarkIlV** [comment]
好的，我试试

**Comment by xianyukang** [comment]
MyKeymap 2.0 支持修改前置键
