### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by shiwenduanzi** [xianyukang/MyKeymap#4]
运行提示“无法定位程序输入点"SetProcessDpiAwarenessContext"于动态链接库User32.dll上

**Comment by xianyukang** [comment]
这个系统 API 在 Windows 10 version 1703 以上才有。

**Comment by xianyukang** [comment]
这个 commit 支持了 win7: https://github.com/xianyukang/MyKeymap/commit/50f6cf71032ff6b1b97c869cf7e87522064eeb1a
