### ISSUE TITLE
考虑下窗口最大化和窗口居中二合一？

### ISSUE THREAD

**Issue by Faith-Mian** [xianyukang/MyKeymap#40]
窗口最大化
窗口居中(1200x800
窗口居中(1370x930
---
感觉这几个功能占的键位有些多，而且最大化没有还原效果，能不能考虑就用一个键按一次最大化，再按一次窗口居中1200x800，依次循环？可以腾出来键，默认配置加入caps+e和caps+d当作“切换应用”届的j+e和j+d，更符合直觉？

**Comment by Faith-Mian** [comment]
> (1) 好的, 下个版本做成「 最大化 」和「 从最大化还原到原来的样子 」 (2) 感觉最大化和居中还是拆成两个键比较好 (3) 没听懂 "加入....和j+d", 能再解释下吗?

我是说仿照J+E=上，J+D=下，默认配置这么设计，CAPS+E=上一个窗口（Alt+Esc)   ，CPAS+D = 下一个窗口（Shift+A1t+Esc

**Comment by xianyukang** [comment]
好的,  我再优化下默认配置
