### ISSUE TITLE
关于设置与配置的一些不重要的现象

### ISSUE THREAD

**Issue by Faith-Mian** [xianyukang/MyKeymap#41]
阿康你好，下面没有要紧事，看看就好。

1. 我删掉了\data\config.json，打开软件设置，命令行会报错无法进入，要不检测json不存在时，载入默认设置？
2. 我用另一份json配置替换了当前配置，重启软件发现配置没有更新，必须进入设置页面重新保存一下才生效。
3. 设置-开关/设置-各模式开关，要不去掉这个页面，把开关放在左侧边栏每个项目的右边？没有开关的【Capslock 指令】和【缩写功能】可以在右侧显示【未绑定】或者已绑定的键位【caps up】，至于左侧边栏是固定顺序排列，还是已开启的功能置顶，我不懂哈哈

**Comment by xianyukang** [comment]
(1) 好的,  这个可以做
(2) 覆盖 config.json 后立即生效,  这个改动量比较大、会失去 JavaScript 处理 json 配置的便利性
(3) 目前的 UI 没有大问题,  就暂时保持现状吧
