### ISSUE TITLE
修改调整音量程序快捷键

### ISSUE THREAD

**Issue by Leiyi548** [xianyukang/MyKeymap#42]
我是一个游戏爱好者，经常打游戏，习惯用wasd来进行上下左右。这样我更喜欢。
我看MyKeymap里面没有这个修改键位。我看了源码这个是exe。我建议可以再搞个wasd版本的exe，然后这样和我一样需求的人也能够愉快的调整。

**Comment by xianyukang** [comment]
把这个 SoundControl-WSAD.exe 改个名字,  覆盖原来的文件应该就行了:
https://github.com/xianyukang/MyKeymap/blob/main/SoundControl-WSAD.exe

**Comment by Leiyi548** [comment]
@xianyukang ok

**Comment by Leiyi548** [comment]
> 把这个 SoundControl-WSAD.exe 改个名字, 覆盖原来的文件应该就行了: https://github.com/xianyukang/MyKeymap/blob/main/SoundControl-WSAD.exe

autohotkey v2 版本没有这个功能了，而且我以前的 x 静音也没用了。

**Comment by xianyukang** [comment]
链接过期了，试试这个文件:
https://github.com/xianyukang/MyKeymap/blob/61fe2520c1845a6437883c92d64dec681639ede2/SoundControl-WSAD.exe
