### ISSUE TITLE
设置切换输入法快捷键shift+ctrt失败

### ISSUE THREAD

**Issue by LDmoxeii** [xianyukang/MyKeymap#45]
设置切换输入法快捷键shift+ctrl失败
使用的是sendevent,　{^+}

**Comment by xianyukang** [comment]
这两个都试试:
(1) sendevent, #{space}
(2) sendevent, {lcontrol down}{lshift down}{lshift up}{lcontrol up}

**Comment by LDmoxeii** [comment]
谢谢，第一个成功，第二个失败。

**Comment by LDmoxeii** [comment]
问题解决了
