### ISSUE TITLE
开启软件玩mc的时候出现鼠标键盘严重延迟

### ISSUE THREAD

**Issue by chinabestcountry** [xianyukang/MyKeymap#47]
开着软件玩mc在游戏内会出现鼠标键盘出现严重延迟，关闭软件后恢复正常
系统win10，没有任何错误报告
请帮帮我:)

**Comment by xianyukang** [comment]
没错开启「 右键模式 」后右键会有延迟
(1) 要么单击托盘图标暂停 MyKeymap
(2) 要么去设置里关掉右键模式

**Comment by chinabestcountry** [comment]
多谢！
问题解决了
:D
