### ISSUE TITLE
键盘控制鼠标的键位使用不同应用配置后两级变速失效

### ISSUE THREAD

**Issue by LDmoxeii** [xianyukang/MyKeymap#48]
因为我在使用某些软件时键盘控制鼠标的键位会经常误触，所以我将原本键盘控制鼠标的键位更换成其他映射。在使用中发现，配置了不同映射的键位，键盘控制鼠标功能中两级变速失效。

**Comment by xianyukang** [comment]
2.0 解决了你说的问题，可以等正式版，或者进群获取 beta 版本
