### ISSUE TITLE
请问是否考虑开放数字键作为窗口的映射？

### ISSUE THREAD

**Issue by BruceZP** [xianyukang/MyKeymap#5]
这样就不需要用f键来组合，将3次按键改变成为2次，大大提高效率（鉴于现在用的窗口不会太多，数字键也是够用的）。

**Comment by xianyukang** [comment]
你是指 Capslock 加数字键绑定窗口吗 ?  
相比于主键区的字母键,  数字键不好按、做不到盲打,  所以不推荐
如果想用两个键绑定窗口的话,  Tab 模式可以做到

**Comment by BruceZP** [comment]
不好意思，大神，才看到你的回复。
我想着用AHK写一个简单功能的脚本，但是我的编程知识相对有限，没法实现Capslock+Num映射到窗口的功能，请问您能否指点一下。

目前我写的是：
;----CapsLock Programme----

CapsLock & 1::
If WinActive("ahk_class CabinetWClass ahk_exe Explorer.EXE")
{
winActivate, ahk_exe chrome.exe
}
Else
{
Run, chrome.exe
}
Return
可是没法实现相应的功能。

请问是哪里出了问题，或者应该用那些函数或指令呢，谢谢。

**Comment by xianyukang** [comment]
CapsLock & 1::
If WinExist("ahk_exe chrome.exe") {
    winActivate, ahk_exe chrome.exe
}
Else {
    Run, chrome.exe
}

**Comment by BruceZP** [comment]
感谢您的指点，根据您的代码，我修改了一下，达到了我个人舒服的调用方式。

CapsLock & 1::
If WinActive("ahk_exe chrome.exe") {
WinMinimize, ahk_exe chrome.exe
}
Else If WinExist("ahk_exe chrome.exe"){
WinActivate, ahk_exe chrome.exe
}
Else {
Run, chrome.exe
}
Return
