### ISSUE TITLE
[功能] 可以加一个 Ctrl 模式吗？或者添加个自定义模式，让用户自己定义触发模式的前置按键，我需要指定LCtrl和LAlt模式，但我不知道该怎么做

### ISSUE THREAD

**Issue by jiangmaniu** [xianyukang/MyKeymap#50]

**Comment by xianyukang** [comment]
可以用这个功能:
![image](https://user-images.githubusercontent.com/24707226/216888364-be814358-c3fb-4802-9823-ed6c8c25a5a8.png)

**Comment by jiangmaniu** [comment]
@xianyukang 感谢你的回复，请问`自定义热键`有触发条件吗？

**Comment by xianyukang** [comment]
嗯、可以试试、应该有

**Comment by jiangmaniu** [comment]
@xianyukang 很抱歉，我并不知道`自定义热键`功能的触发前置按键是什么，阅读相关文档没有找到答案。我试图直接按热键定义的快捷按键，但似乎不起作用

![image](https://user-images.githubusercontent.com/50100681/216888987-42421220-23d2-4a14-a432-a2c6d537477c.png)

**Comment by xianyukang** [comment]
这个应该行:

![image](https://user-images.githubusercontent.com/24707226/216890957-da3e7038-2bb9-4736-9268-08a577060a50.png)

![image](https://user-images.githubusercontent.com/24707226/216891027-b3a38c84-2fdd-4c19-a4dc-c159c62261f2.png)

**Comment by jiangmaniu** [comment]
我似乎明白是什么问题了，好像是我设置了`按键重映射`的问题

![image](https://user-images.githubusercontent.com/50100681/216906531-add4ea93-4912-490c-b10b-bc099185610b.png)

![image](https://user-images.githubusercontent.com/50100681/216906628-e6f23176-d11b-4481-bce6-c8467046c8cb.png)

我以为将 CapsLock 映射为 LCtrl，在`自定义热键`里面的^也会被映射为 CapsLock，`CapsLock + H` 应该与 `Ctrl + H` 一样都能触发`Left`，但测试的结果并不是我想的那样，这两个功能似乎 会冲突。

当我删除`按键重映射`的设置时，使用 `Ctrl + H` 能够被 `自定义热键` 映射为 `Left`。

请问如何在设置 `按键重映射` 的同时，依旧可以使用 `自定义热键` ？

**Comment by xianyukang** [comment]
1. 不清楚啊,  我没有这方面的经验
2. 如果想要更灵活的映射, 推荐学一下 ahk 语言

**Comment by jiangmaniu** [comment]
想知道大佬为啥不考虑做一个`自定义模式` ，让用户自己定义触发模式的前置按键的功能？

**Comment by xianyukang** [comment]
1. 想偷懒、希望避免复杂性
2. 已经提供了若干个预定义的/好用的 `引导键` 供用户选择,  暂时没动力做一个 `自定义模式`

**Comment by jiangmaniu** [comment]
我主要是用vim编辑器和快捷键的，所以我比较需要自定义的快捷键，如果能做自定义模式的话，我想受众的用户群体会更多，自由度和可玩性也会更高。

**Comment by xianyukang** [comment]
自定义模式做出来了，可以等正式版，或者进群获取 beta 版本
