### ISSUE TITLE
3模式下0键映射成+不好使

### ISSUE THREAD

**Issue by beyond7100** [xianyukang/MyKeymap#53]
我尝试想把3模式下的0键设置成+, 这样0p;/这四个键就可以分别对应+-*/, 但是当我设置3模式下0键映射成+之后发现不好使, 如果映射成其他符号(比如减号)就没有问题, 只有加号不行
![image](https://user-images.githubusercontent.com/65872336/221770922-70c0ad07-a67a-4f08-a83e-3d38a03e41b5.png)

**Comment by xianyukang** [comment]
- 因为 + 号在 AutoHotkey 中是特殊符号，可以用 +{home} 表示 Shift + Home 热键
- 可以用 `{+}` 表示想输入 + 符号
