### ISSUE TITLE
关于新软件和旧配置

### ISSUE THREAD

**Issue by Faith-Mian** [xianyukang/MyKeymap#54]
阿康你好，今天升级到了最新版本，差点丢了配置文件，因为新软件的默认配置覆盖了原来的config.json，还好有备份。考虑一下默认不带config.json交由主程序启动检测不存在则生成配置？

还有记得以前讨论过，程序运行时刻检测配置文件变动没必要，那考虑一下主程序启动即重新读取最新config.json，升级软件继承配置直接生效不用进配置页面保存？

**Comment by xianyukang** [comment]
从 2.0 开始，升级到 2.0 之后的版本
升级时只需用旧的 config.json 覆盖一下，无需进入设置页面保存
