### ISSUE TITLE
[Bug]Tab按键，使用后，Tab键就跟按着不动似的，一直触发着

### ISSUE THREAD

**Issue by akatong** [xianyukang/MyKeymap#56]
我是用Tab+某个按键，触发一些功能，例如：窗口移动到另一个显示器；快速打开某个程序，等等
但是，经常出现按下Tab+某个按键后，这个Tab就跟按着不动一样，下一次直接按第二个按键，就直接输出了想要的功能。。。
导致我打字的时候，动不动触发了。。。都没按Tab就触发。。
我怀疑是跟某个程序冲突了，还是怎么的。
我现在使用的程序有：
Listary
Altdrag
Snipaste
WGestures
这些效率软件

**Comment by Faith-Mian** [comment]
mouseinc没记错的话包含了拖拽移动窗口和鼠标手势两个功能，可以取代altdrag & wgestures，当然要解决问题的话，还是控制变量，4个软件依次关闭其中一个看看情况有没有变化。

**Comment by alexcchen** [comment]
Capslock+/, 将/键映射为Rctrl, 使用起来会一直触发Rctrl键，导致无法输入任何内容，目前曲线救国，把/ 键作为CapsLock的下一级触发，再把所有用到的字母按键重映射为^加字母，放到触发里面使用

**Comment by xianyukang** [comment]
> Capslock+/, 将/键映射为Rctrl, 使用起来会一直触发Rctrl键，导致无法输入任何内容，目前曲线救国，把/ 键作为CapsLock的下一级触发，再把所有用到的字母按键重映射为^加字母，放到触发里面使用

- 不算 bug，松开 Capslock 后 / 键就失去了 RCtrl 的作用
- 按住 Capslock 的前提下松开 / 键则没问题，卡住是因为松开 / 时没有释放 RCtrl 键

**Comment by alexcchen** [comment]
我松开Capslock后，是继续按住/键的，此时相当于按住了RCtrl键，再接着按个w键，执行一次Ctrl加w关闭页面成功，松开全部按键，之后就发现RCtrl处于一直按下的状态（因为我此时只用滑动滑轮页面就会放大缩小，点击t就会新建页面，不需要按Ctrl），重启暂停设置把mykeymap关闭后还是存在RCtrl一直按下的情况，只能进行注销电脑账户重新登录后才会恢复

**Comment by alexcchen** [comment]
我的Capslock组合w是设置为打开指定软件的，不知道是否会导致这个冲突

**Comment by xianyukang** [comment]
@alexcchen 
1. 必须在按住 Capslock 键的前提下松开 / 键
2. 没必要注销电脑，再按一次 Capslock+/ 就行，手动按键盘上的 RCtrl 键也行
3. 和打开指定软件没关系，不会导致冲突。用前面提到的「 曲线救国 」那种配法就行

**Comment by alexcchen** [comment]
谢谢，您说的解决方法真实有效
