### ISSUE TITLE
[BUG] 移动窗口到下一个显示器，缩放比例不同，会导致窗口变形。

### ISSUE THREAD

**Issue by huxc573** [xianyukang/MyKeymap#57]
使用自带功能“移动窗口到下一个显示器”的快捷键，如果两个显示器在windows中设置的缩放比例不同，会导致窗口变形，包括分辨率和横竖比例。
如果单纯是鼠标拖动窗口到下一个显示器，windows会自动按照原显示器窗口比例进行缩放，不会出现比例不同的情况。
如果可行，希望“移动窗口到下一个显示器”能按照windows的逻辑对窗口进行处理。

**Comment by xianyukang** [comment]
移动窗口到下一个显示器，调用的就是 Windows 自带的 Win + Shift + Right 热键，看来是 Windows 的处理不够完善
