### ISSUE TITLE
caps切换延迟

### ISSUE THREAD

**Issue by Legroft** [xianyukang/MyKeymap#6]
开启后按caps会延迟个零点几秒左右才切换，导致飞速敲代码时候写驼峰很不舒服

**Comment by xianyukang** [comment]
单独关闭了 Capslock 指令对吗?  如果是这样的话,  需要等 Caps 抬起时才能切换大小写。

~~( 用 Shift 键写驼峰比 Caps 方便,  因为 Caps 需要来回切换大小写状态。~~

**Comment by Legroft** [comment]
原来如此
