### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Charbddlie** [xianyukang/MyKeymap#60]
大佬你好，我想使用这款软件取代home和end以及方向键之类的操作，然后我想获得一个功能：**通过快捷键开关某一种按键映射**
比如按下capslock后，我的ijkl变成上下左右的映射，uo变成home和end的映射，但是我在设置网页中好像没有发现相关的实现，请问已经实现了吗？

**Comment by jojo996** [comment]
现在能实现的是按下capslock之后能够进行按键映射，但是首先感觉不太符合直觉，其次对于按键按下的顺序也有要求，比如要实现shift选中加上home和end对应的按键就需要先按capslock再按shift再按映射按键（比如u），所以使用体验感觉不太行

**Comment by jojo996** [comment]
现在能实现的是按下capslock之后能够进行按键映射，但是首先感觉不太符合直觉，其次对于按键按下的顺序也有要求，比如要实现shift选中加上home和end对应的按键就需要先按capslock再按shift再按映射按键（比如u），所以使用体验感觉不太行

**Comment by xianyukang** [comment]
> 现在能实现的是按下capslock之后能够进行按键映射，但是首先感觉不太符合直觉，其次对于按键按下的顺序也有要求
- 首先这很符合直觉，著名的 Emacs 就是这样的，使用组合键 Ctrl + f/b/n/p 表示上下左右

> 通过快捷键开关某一种按键映射
- 可以下载 MyKeymap 2.0，然后把 Capslock 的 SinglePress 配成「 锁定当前模式 」
- 就能按 Capslock 键开关一种按键映射
