### ISSUE TITLE
功能优化 - 在切换窗口时，是否可以把鼠标的焦点也切换到激活的窗口？ 

### ISSUE THREAD

**Issue by feitian6186** [xianyukang/MyKeymap#61]
尊敬的UP主，你好？ 

        我有两块显示器，在使用电脑时，两个电脑分别开不同的应用程序，我会使用 “模拟 Alt + Tab 热键” 进行两个窗口程序的切换，但是使用“滚轮下滑“时，却发现鼠标还停留在上一个程序的窗口处，如果上一个程序在另一个显示器的话就比较麻烦，我不得不使用”移动鼠标到输入焦点“来进行二次操作，有点麻烦。

**是否可以在切换窗口时，自动把鼠标焦点切换过来？**

**Comment by xianyukang** [comment]
鼠标操作中有这个功能「 移动鼠标到活动窗口 」

**Comment by feitian6186** [comment]
虽然有" 移动鼠标到活动窗口"这个功能，但是需要二次操作。是否可以在切换窗口的同时，同步执行"移动鼠标到活动窗口“这个功能，这样在双屏的情况下，免去多余的步骤

**Comment by xianyukang** [comment]
试试这段代码，可能要 beta29 版本:
> ahk: Send("!{tab}")
> ahk: Sleep(200)
> ahk: MoveMouseToCaret()

![image](https://github.com/user-attachments/assets/8e715a81-208e-49cd-8c32-5463aee83c90)
