### ISSUE TITLE
功能建议: 添加关闭 [Capslock命令] 的选项

### ISSUE THREAD

**Issue by Nashmatphysics** [xianyukang/MyKeymap#66]
你好, 感谢提供这么棒的工具, 但是有一个问题最近困扰着我: 我使用listary启动应用程序, 因为它的工具条可以模糊搜素, 就像这样:

![Image-20230724125254](https://github.com/xianyukang/MyKeymap/assets/25275896/62b5edce-8ce9-41f4-a709-a719565cf5c7)

我想将打开listary搜素框的快捷键映射到`Capslock`按键, 这与mykeymap有冲突, 因为mykeymap没有关闭`Capslock命令`的选项:

![Image-20230724125650](https://github.com/xianyukang/MyKeymap/assets/25275896/1002d492-3883-4276-83f4-97d64b979b03)

所以能否单独添加一个关闭`Capslock命令`的按钮.

**Comment by xianyukang** [comment]
(1) Capslock 模式中有个 「 Caps Up 」, 你可以把这个键配成输入 Ctrl+Alt+L ( 假设这是 Listary 的激活热键 )

(2) 只要你把 「 Caps Up 」键配成其他功能，就相当于关掉了 Capslock 命令

**Comment by Nashmatphysics** [comment]
谢谢! 成功解决了我的麻烦, 之前找了一个C#程序通过键盘钩子来解决这个问题. 你的方法更加简洁而优雅.
