### ISSUE TITLE
在windows terminal中使用wsl(ubuntu）的时候，j+t失效，j+b行为不正确。

### ISSUE THREAD

**Issue by predawnang** [xianyukang/MyKeymap#67]
你好
       
我在windows terminal打开wsl的时候。在命令行里面使用j+t删除到行尾没有效果，可能是哪里冲突了，wsl的tab那边会显示一个小铃铛。然后j+b从删除一个单词，变成只删除一个字符。
我在windows terminal中使用powershell则没有这个问题。

谢谢

**Comment by xianyukang** [comment]
1. 这个是因为 Linux Shell 中不支持用 Ctrl+BackSpace 删除单词
2. Linux Shell 中删除单词的热键为 Ctrl+W，更多热键[参考这里](https://www.makeuseof.com/linux-bash-terminal-shortcuts/#:~:text=argument%20n%20to%20%24)-,Bash%20Editing,-Ctrl%20%2B%20U)

**Comment by xianyukang** [comment]
- 通过修改 Shell的 的配置，也能让它支持 Ctrl+BackSpace 删除单词
- 具体参考这个 issue:
- https://github.com/microsoft/terminal/issues/755#issuecomment-530905894
