### ISSUE TITLE
Win11窗口操作中EDSF不生效

### ISSUE THREAD

**Issue by cbconne** [xianyukang/MyKeymap#7]
Caps+E进入窗口操作后EDSF无法控制选中窗口，X也无法关闭选中窗口
~虽然知道大概率是win11导致的问题~

version: 1.0.22
操作系统：win11

**Comment by xianyukang** [comment]
> Caps+E进入窗口操作后EDSF无法控制选中窗口，X也无法关闭选中窗口 ~虽然知道大概率是win11导致的问题~
> 
> version: 1.0.22 操作系统：win11

1.0.23 修复了这个问题
