### ISSUE TITLE
为什么不提供 [Capslock 命令] 的开关选项呀

### ISSUE THREAD

**Issue by arpir** [xianyukang/MyKeymap#89]
因为我不想启用 Capslock 命令框，因此在 Caps 模式中把 Caps Up 分配成什么也不做，这样达到禁用 Capslock+F、Capslock+Space、Capslock 命令的作用，然后开关设置里面也提供了关闭 Capslock+F、Capslock+Space 的开关，但是唯独没有  Capslock 命令的开关，MyKeymap 的功能太强大啦，需要仔细阅读文档才能按自己的习惯完成配置，这样能最大程度减少非自己需求功能上的干扰。 通常配置好之后就不会再动了，假如很长时间没有打开设置，我大概就会忘了这个 Capslock 命令模块到底是怎么用的 (因为事实上它已经被禁用了)但是它又不能隐藏而像 Capslock+F、Capslock+Space 提供了开关。

**Comment by xianyukang** [comment]
- 不配命令框的触发键就能在事实上关掉「 Capslock 命令 」
- 这时候再加上你说的开关，不就有两个开关了吗? 会把问题搞复杂

**Comment by arpir** [comment]
> 目的就是隐藏掉不需要的功能，有那么难理解吗。因为功能太多了也不是个人需要的，只开启自己需要的，减少记忆。现在是Capslock 命令会始终在侧边栏存在呀，但是我已经关掉了它的功能

**Comment by xianyukang** [comment]
> 目的就是隐藏掉不需要的功能
  - 好的，以后加个隐藏按钮
> 有那么难理解吗
  - 不难理解呀，你无需怀疑的自己的表达能力

**Comment by arpir** [comment]
😂😁

**Comment by xianyukang** [comment]
应该解决了你说的问题，可以进群获取 beta2 内测版本，或等正式版
