### ISSUE TITLE
关于映射在组合键不起作用的问题

### ISSUE THREAD

**Issue by MasouShizuka** [xianyukang/MyKeymap#97]
切换到 2 版本后，映射在组合键中不会起作用。

比如空格模式，将 `A` 键 映射为 `Send({blind}1)`，按 `space+a` 能输出 `1`。
但是比如其他程序中我设置了一个快捷键 `alt+1`，在 1 版本我可以按 `alt+space+a` 来触发，而在 2 版本却不行。

我想问下这个能在 2 版本中实现吗？还是说这是 ahk v2 的改变呢

顺便一提，`bin/lib/Fcunctions.ahk` 是不是命名错了（

**Comment by xianyukang** [comment]
需要为空格模式的触发键加上 * 号，从 `space` 改成 `*space`
确实名字写错了，等会改掉
