### ISSUE TITLE
新版问题，ProcessExistSendKeyOrRun函数和窗口绑定

### ISSUE THREAD

**Issue by meetyoucrash** [xianyukang/MyKeymap#99]
现在用ProcessExistSendKeyOrRun函数有些问题，可以正常启动程序，但是程序已经启动的时候，并不是都能正常发送快捷键。
比如我ProcessExistSendKeyOrRun("MouseInc.exe", "^!o", "shortcuts\MouseInc.lnk")，就不能在MouseInc.exe已经启动的时候发送^!o快捷键。但是示例中启动激活微信我试过又很正常。

还有绑定当前窗口这个操作现在有问题，一按就会程序报错，推测是对长按短按的动作识别有问题

**Comment by xianyukang** [comment]
解决了，麻烦试一下新版本

**Comment by meetyoucrash** [comment]
好的，我一会看看，我现在在群里了，在群里说了我就知道



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月13日(周三) 中午1:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xianyukang/MyKeymap] 新版问题，ProcessExistSendKeyOrRun函数和窗口绑定 (Issue #99)




 
解决了，麻烦试一下新版本
